import {
  User,
  MatrimonialProfile,
  InterestRequest,
  FavoriteItem,
  Conversation,
  ChatMessage,
  NotificationItem,
  SubscriptionPlan,
  Invoice,
  VerificationRequest,
  AbuseReport,
  SupportTicket,
  Coupon,
  CMSContent,
  AdminAuditLog,
  SystemSettings,
  PaymentProof,
  ReceivingAccount,
  ExtraConnectionPack,
  Consultant,
  ConnectionTransaction,
} from './types';

// ============================================================================
// 1. SYSTEM USERS (1 Super Admin + 10 Boys + 10 Girls = 21 Real Users)
// ============================================================================
export const INITIAL_USERS: User[] = [
  // SUPER ADMIN
  {
    id: 'user-ladi',
    name: 'Ladi (Super Admin)',
    email: 'ladi02893@gmail.com',
    phone: '+92 300 1234567',
    whatsappNumber: '+92 300 1234567',
    profileIdCode: 'VRM-000001',
    role: 'SUPER_ADMIN',
    subscriptionTier: 'PREMIUM_PLUS',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 300,
    usedConnections: 43,
    remainingConnections: 257,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-01-01T00:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-ladi',
  },
  // [MALE #1] Dr. Hamza Malik
  {
    id: 'user-boy-1',
    name: 'Dr. Hamza Malik',
    email: 'hamza.malik@gmail.com',
    phone: '+92 300 1122334',
    whatsappNumber: '+92 300 1122334',
    profileIdCode: 'VRM-000002',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 30,
    usedConnections: 5,
    remainingConnections: 25,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-1',
  },
  // [MALE #2] Engr. Bilal Ahmed
  {
    id: 'user-boy-2',
    name: 'Engr. Bilal Ahmed',
    email: 'bilal.ahmed@gmail.com',
    phone: '+92 301 4455667',
    whatsappNumber: '+92 301 4455667',
    profileIdCode: 'VRM-000003',
    role: 'USER',
    subscriptionTier: 'PREMIUM',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 100,
    usedConnections: 12,
    remainingConnections: 88,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-2',
  },
  // [MALE #3] Usman Tariq
  {
    id: 'user-boy-3',
    name: 'Usman Tariq',
    email: 'usman.tariq@gmail.com',
    phone: '+92 321 8899001',
    whatsappNumber: '+92 321 8899001',
    profileIdCode: 'VRM-000004',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 30,
    usedConnections: 5,
    remainingConnections: 25,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-3',
  },
  // [MALE #4] Ali Raza Kazmi
  {
    id: 'user-boy-4',
    name: 'Ali Raza Kazmi',
    email: 'ali.raza@gmail.com',
    phone: '+92 333 5566778',
    whatsappNumber: '+92 333 5566778',
    profileIdCode: 'VRM-000005',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 30,
    usedConnections: 5,
    remainingConnections: 25,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-4',
  },
  // [MALE #5] Shahzad Arain
  {
    id: 'user-boy-5',
    name: 'Shahzad Arain',
    email: 'shahzad.arain@gmail.com',
    phone: '+92 300 7788990',
    whatsappNumber: '+92 300 7788990',
    profileIdCode: 'VRM-000006',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 30,
    usedConnections: 5,
    remainingConnections: 25,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-5',
  },
  // [MALE #6] Farhan Cheema
  {
    id: 'user-boy-6',
    name: 'Farhan Cheema',
    email: 'farhan.cheema@gmail.com',
    phone: '+92 322 3344556',
    whatsappNumber: '+92 322 3344556',
    profileIdCode: 'VRM-000007',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 30,
    usedConnections: 5,
    remainingConnections: 25,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-6',
  },
  // [MALE #7] Dr. Hassan Niazi
  {
    id: 'user-boy-7',
    name: 'Dr. Hassan Niazi',
    email: 'hassan.niazi@gmail.com',
    phone: '+92 345 6677889',
    whatsappNumber: '+92 345 6677889',
    profileIdCode: 'VRM-000008',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 30,
    usedConnections: 5,
    remainingConnections: 25,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-7',
  },
  // [MALE #8] Waleed Sheikh
  {
    id: 'user-boy-8',
    name: 'Waleed Sheikh',
    email: 'waleed.sheikh@gmail.com',
    phone: '+92 334 9900112',
    whatsappNumber: '+92 334 9900112',
    profileIdCode: 'VRM-000009',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 30,
    usedConnections: 5,
    remainingConnections: 25,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-8',
  },
  // [MALE #9] Taimoor Abbasi
  {
    id: 'user-boy-9',
    name: 'Taimoor Abbasi',
    email: 'taimoor.abbasi@gmail.com',
    phone: '+92 312 3322110',
    whatsappNumber: '+92 312 3322110',
    profileIdCode: 'VRM-000010',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 30,
    usedConnections: 5,
    remainingConnections: 25,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-9',
  },
  // [MALE #10] Danyal Memon
  {
    id: 'user-boy-10',
    name: 'Danyal Memon',
    email: 'danyal.memon@gmail.com',
    phone: '+92 300 4433221',
    whatsappNumber: '+92 300 4433221',
    profileIdCode: 'VRM-000011',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 30,
    usedConnections: 5,
    remainingConnections: 25,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-10',
  },
  // [FEMALE #1] Amna Khan
  {
    id: 'user-amna',
    name: 'Amna Khan',
    email: 'amna.khan@gmail.com',
    phone: '+92 300 1234567',
    whatsappNumber: '+92 300 1234567',
    profileIdCode: 'VRM-000012',
    role: 'USER',
    subscriptionTier: 'PREMIUM_PLUS',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 300,
    usedConnections: 43,
    remainingConnections: 257,
    assignedConsultantId: 'consultant-1',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-amna',
  },
  // [FEMALE #2] Dr. Zainab Qureshi
  {
    id: 'user-girl-2',
    name: 'Dr. Zainab Qureshi',
    email: 'zainab.qureshi@gmail.com',
    phone: '+92 333 1122445',
    whatsappNumber: '+92 333 1122445',
    profileIdCode: 'VRM-000013',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 30,
    usedConnections: 5,
    remainingConnections: 25,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-2',
  },
  // [FEMALE #3] Fatima Zahra Kazmi
  {
    id: 'user-girl-3',
    name: 'Fatima Zahra Kazmi',
    email: 'fatima.zahra@gmail.com',
    phone: '+92 321 9988776',
    whatsappNumber: '+92 321 9988776',
    profileIdCode: 'VRM-000014',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 30,
    usedConnections: 5,
    remainingConnections: 25,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-3',
  },
  // [FEMALE #4] Areeba Rajput
  {
    id: 'user-girl-4',
    name: 'Areeba Rajput',
    email: 'areeba.rajput@gmail.com',
    phone: '+92 301 7766554',
    whatsappNumber: '+92 301 7766554',
    profileIdCode: 'VRM-000015',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 30,
    usedConnections: 5,
    remainingConnections: 25,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-4',
  },
  // [FEMALE #5] Mariam Arain
  {
    id: 'user-girl-5',
    name: 'Mariam Arain',
    email: 'mariam.arain@gmail.com',
    phone: '+92 300 8877665',
    whatsappNumber: '+92 300 8877665',
    profileIdCode: 'VRM-000016',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 30,
    usedConnections: 5,
    remainingConnections: 25,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-5',
  },
  // [FEMALE #6] Hira Siddiqui
  {
    id: 'user-girl-6',
    name: 'Hira Siddiqui',
    email: 'hira.siddiqui@gmail.com',
    phone: '+92 334 2233445',
    whatsappNumber: '+92 334 2233445',
    profileIdCode: 'VRM-000017',
    role: 'USER',
    subscriptionTier: 'PREMIUM',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 100,
    usedConnections: 12,
    remainingConnections: 88,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-6',
  },
  // [FEMALE #7] Noor-ul-Ain Malik
  {
    id: 'user-girl-7',
    name: 'Noor-ul-Ain Malik',
    email: 'noor.malik@gmail.com',
    phone: '+92 308 1122339',
    whatsappNumber: '+92 308 1122339',
    profileIdCode: 'VRM-000018',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 30,
    usedConnections: 5,
    remainingConnections: 25,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-7',
  },
  // [FEMALE #8] Ayesha Butt
  {
    id: 'user-girl-8',
    name: 'Ayesha Butt',
    email: 'ayesha.butt@gmail.com',
    phone: '+92 323 4455667',
    whatsappNumber: '+92 323 4455667',
    profileIdCode: 'VRM-000019',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 30,
    usedConnections: 5,
    remainingConnections: 25,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-8',
  },
  // [FEMALE #9] Dr. Mahnoor Gujjar
  {
    id: 'user-girl-9',
    name: 'Dr. Mahnoor Gujjar',
    email: 'mahnoor.gujjar@gmail.com',
    phone: '+92 300 9988112',
    whatsappNumber: '+92 300 9988112',
    profileIdCode: 'VRM-000020',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 30,
    usedConnections: 5,
    remainingConnections: 25,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-9',
  },
  // [FEMALE #10] Sara Abbasi
  {
    id: 'user-girl-10',
    name: 'Sara Abbasi',
    email: 'sara.abbasi@gmail.com',
    phone: '+92 313 7788990',
    whatsappNumber: '+92 313 7788990',
    profileIdCode: 'VRM-000021',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    profileApprovalStatus: 'APPROVED',
    isVerified: true,
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    totalConnections: 30,
    usedConnections: 5,
    remainingConnections: 25,
    assignedConsultantId: undefined,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-10',
  },
];

// ============================================================================
// 2. MATRIMONIAL PROFILES (1 Super Admin + 10 Boys + 10 Girls = 21 Profiles)
// ============================================================================
export const INITIAL_PROFILES: MatrimonialProfile[] = [
  // SUPER ADMIN PROFILE
  {
    id: 'profile-ladi',
    userId: 'user-ladi',
    profileIdCode: 'VRM-000001',
    fullName: 'Ladi (Super Admin)',
    displayName: 'Ladi',
    gender: 'MALE',
    dateOfBirth: '1995-05-15',
    age: 30,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Syed',
    motherTongue: 'Urdu',
    phone: '+92 300 1234567',
    whatsappNumber: '+92 300 1234567',
    city: 'Lahore',
    state: 'Punjab',
    province: 'Punjab',
    area: 'DHA Phase 5',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Super Administrator & Matchmaking Executive Director',
    aboutMe: 'Official Executive Director for VIP Royal Matchmaking. Dedicated to ensuring family trust, verified profiles, and discrete matrimonial connections.',
    completionPercentage: 100,
    isFeatured: true,
    isBoosted: true,
    approvalStatus: 'APPROVED',
    viewCount: 120,
    likeCount: 45,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: true,
    educationCareer: {
      highestDegree: "Master's in Computer Science",
      institution: 'LUMS Lahore',
      profession: 'Executive Director & Tech Architect',
      annualIncome: 'PKR 10 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 10\"",
      weight: '74 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu',
      languagesSpoken: ['English', 'Urdu', 'Punjabi'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Retired Civil Servant',
      motherOccupation: 'Educator & Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Lahore, Pakistan',
      familyCity: 'Lahore',
      aboutFamily: 'Respected, educated family with high ethical standards.',
    },
    partnerPreferences: {
      minAge: 22,
      maxAge: 30,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking a sincere, educated life partner with good moral values.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-ladi-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #1] Dr. Hamza Malik
  {
    id: 'profile-boy-1',
    userId: 'user-boy-1',
    profileIdCode: 'VRM-000002',
    fullName: 'Dr. Hamza Malik',
    displayName: 'Dr.',
    gender: 'MALE',
    dateOfBirth: '1996-04-12T00:00:00Z',
    age: 29,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Malik',
    motherTongue: 'Punjabi / Urdu',
    phone: '+92 300 1122334',
    whatsappNumber: '+92 300 1122334',
    city: 'Lahore',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Gulberg III',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Cardiologist (FCPS) at Punjab Institute of Cardiology (PIC)',
    aboutMe: 'Practicing Cardiologist at PIC Lahore. Balance religious ethics with professional medical career. Looking for an educated, family-oriented partner with similar values.',
    completionPercentage: 88,
    isFeatured: true,
    isBoosted: true,
    approvalStatus: 'APPROVED',
    viewCount: 33,
    likeCount: 11,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: true,
    consultantNote: 'Cardiologist from a noble background, highly recommended based on family preferences and educational alignment.',
    educationCareer: {
      highestDegree: 'MBBS, FCPS Cardiology',
      institution: 'King Edward Medical University (KEMU)',
      profession: 'Cardiologist',
      annualIncome: 'PKR 4.2 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 11\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Punjabi / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Lahore, Pakistan',
      familyCity: 'Lahore',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 22,
      maxAge: 28,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-boy-1-1',
        url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #2] Engr. Bilal Ahmed
  {
    id: 'profile-boy-2',
    userId: 'user-boy-2',
    profileIdCode: 'VRM-000003',
    fullName: 'Engr. Bilal Ahmed',
    displayName: 'Engr.',
    gender: 'MALE',
    dateOfBirth: '1997-06-15T00:00:00Z',
    age: 28,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Syed',
    motherTongue: 'Urdu',
    phone: '+92 301 4455667',
    whatsappNumber: '+92 301 4455667',
    city: 'Islamabad',
    state: 'Punjab',
    province: 'Punjab',
    area: 'F-10',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Principal AI/Cloud Architect (NUST) | Tech Consultant',
    aboutMe: 'Lead AI Engineer at a US-based cloud consultancy. NUST graduate with a passion for tech, fitness, and family life. Seeking a compatible, caring life partner.',
    completionPercentage: 85,
    isFeatured: true,
    isBoosted: true,
    approvalStatus: 'APPROVED',
    viewCount: 41,
    likeCount: 14,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: true,
    consultantNote: 'Principal AI Cloud Architect at NUST, cultured family residing in F-10 Islamabad.',
    educationCareer: {
      highestDegree: 'MS Computer Science & AI',
      institution: 'NUST Islamabad',
      profession: 'Principal AI/Cloud Architect',
      annualIncome: 'PKR 5.5 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 12\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Islamabad, Pakistan',
      familyCity: 'Islamabad',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 22,
      maxAge: 28,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-boy-2-1',
        url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #3] Usman Tariq
  {
    id: 'profile-boy-3',
    userId: 'user-boy-3',
    profileIdCode: 'VRM-000004',
    fullName: 'Usman Tariq',
    displayName: 'Usman',
    gender: 'MALE',
    dateOfBirth: '1995-09-22T00:00:00Z',
    age: 30,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Rajput',
    motherTongue: 'Urdu / Punjabi',
    phone: '+92 321 8899001',
    whatsappNumber: '+92 321 8899001',
    city: 'Karachi',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Clifton',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Senior Investment Banker (CFA / IBA Karachi)',
    aboutMe: 'Vice President of M&A and Investment Banking at a leading financial institution in Karachi. IBA alumnus, CFA charterholder. Seeking a graceful, intelligent partner.',
    completionPercentage: 94,
    isFeatured: true,
    isBoosted: false,
    approvalStatus: 'APPROVED',
    viewCount: 49,
    likeCount: 17,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: false,
    consultantNote: undefined,
    educationCareer: {
      highestDegree: 'BBA & MBA Finance (IBA), CFA',
      institution: 'Institute of Business Administration (IBA Karachi)',
      profession: 'Senior Investment Banker',
      annualIncome: 'PKR 6.0 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 10\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu / Punjabi',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Karachi, Pakistan',
      familyCity: 'Karachi',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 22,
      maxAge: 28,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-boy-3-1',
        url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #4] Ali Raza Kazmi
  {
    id: 'profile-boy-4',
    userId: 'user-boy-4',
    profileIdCode: 'VRM-000005',
    fullName: 'Ali Raza Kazmi',
    displayName: 'Ali',
    gender: 'MALE',
    dateOfBirth: '1998-03-10T00:00:00Z',
    age: 27,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Shia',
    caste: 'Syed (Kazmi)',
    motherTongue: 'Urdu',
    phone: '+92 333 5566778',
    whatsappNumber: '+92 333 5566778',
    city: 'Rawalpindi',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Bahria Ph 4',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Chartered Accountant (ACA / LUMS) | Senior Auditor',
    aboutMe: 'Chartered Accountant working with Big 4 Audit Firm. LUMS graduate. High regard for family values, faith, and mutual respect in marriage.',
    completionPercentage: 91,
    isFeatured: true,
    isBoosted: false,
    approvalStatus: 'APPROVED',
    viewCount: 57,
    likeCount: 20,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: false,
    consultantNote: undefined,
    educationCareer: {
      highestDegree: 'BSc Accounting & Finance (LUMS), ACA',
      institution: 'LUMS & ICAP',
      profession: 'Chartered Accountant',
      annualIncome: 'PKR 3.8 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 9\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Rawalpindi, Pakistan',
      familyCity: 'Rawalpindi',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 22,
      maxAge: 28,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-boy-4-1',
        url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #5] Shahzad Arain
  {
    id: 'profile-boy-5',
    userId: 'user-boy-5',
    profileIdCode: 'VRM-000006',
    fullName: 'Shahzad Arain',
    displayName: 'Shahzad',
    gender: 'MALE',
    dateOfBirth: '1994-11-05T00:00:00Z',
    age: 31,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Arain',
    motherTongue: 'Punjabi / Urdu',
    phone: '+92 300 7788990',
    whatsappNumber: '+92 300 7788990',
    city: 'Faisalabad',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Civil Lines',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Textile Export Director (FAST-NUCES & UK Graduate)',
    aboutMe: 'Director at an established textile export manufacturing firm in Faisalabad. Educated, well-travelled, grounded in family values. Looking for a polite, graceful partner.',
    completionPercentage: 82,
    isFeatured: false,
    isBoosted: false,
    approvalStatus: 'APPROVED',
    viewCount: 65,
    likeCount: 23,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: false,
    consultantNote: undefined,
    educationCareer: {
      highestDegree: 'BS Industrial Engg (FAST), MSc Supply Chain (UK)',
      institution: 'FAST-NUCES & University of Manchester',
      profession: 'Textile Export Director',
      annualIncome: 'PKR 9.5 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "6' 0\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Punjabi / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Faisalabad, Pakistan',
      familyCity: 'Faisalabad',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 22,
      maxAge: 28,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-boy-5-1',
        url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #6] Farhan Cheema
  {
    id: 'profile-boy-6',
    userId: 'user-boy-6',
    profileIdCode: 'VRM-000007',
    fullName: 'Farhan Cheema',
    displayName: 'Farhan',
    gender: 'MALE',
    dateOfBirth: '1997-08-19T00:00:00Z',
    age: 28,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Jatt (Cheema)',
    motherTongue: 'Punjabi / Urdu',
    phone: '+92 322 3344556',
    whatsappNumber: '+92 322 3344556',
    city: 'Gujranwala',
    state: 'Punjab',
    province: 'Punjab',
    area: 'DC Colony',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Civil Engineer & Construction Contractor (UET Lahore)',
    aboutMe: 'Civil Engineer running family infrastructure construction firm. UET Lahore graduate. Active sportsman, respects family traditions and Islamic values.',
    completionPercentage: 90,
    isFeatured: false,
    isBoosted: false,
    approvalStatus: 'APPROVED',
    viewCount: 73,
    likeCount: 26,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: false,
    consultantNote: undefined,
    educationCareer: {
      highestDegree: 'BSc Civil Engineering (UET Lahore)',
      institution: 'UET Lahore',
      profession: 'Civil Engineer & Contractor',
      annualIncome: 'PKR 4.8 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "6' 1\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Punjabi / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Gujranwala, Pakistan',
      familyCity: 'Gujranwala',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 22,
      maxAge: 28,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-boy-6-1',
        url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #7] Dr. Hassan Niazi
  {
    id: 'profile-boy-7',
    userId: 'user-boy-7',
    profileIdCode: 'VRM-000008',
    fullName: 'Dr. Hassan Niazi',
    displayName: 'Dr.',
    gender: 'MALE',
    dateOfBirth: '1993-12-14T00:00:00Z',
    age: 32,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Niazi (Pathan)',
    motherTongue: 'Pashto / Urdu',
    phone: '+92 345 6677889',
    whatsappNumber: '+92 345 6677889',
    city: 'Peshawar',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Hayatabad',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Orthopedic Surgeon (MBBS, MS Ortho) at HMC Peshawar',
    aboutMe: 'Orthopedic Surgeon at Hayatabad Medical Complex. Humble, dedicated, family-centric. Looking for an educated partner from a respected family.',
    completionPercentage: 85,
    isFeatured: false,
    isBoosted: false,
    approvalStatus: 'APPROVED',
    viewCount: 81,
    likeCount: 29,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: false,
    consultantNote: undefined,
    educationCareer: {
      highestDegree: 'MBBS, MS Orthopedic Surgery',
      institution: 'Khyber Medical College (KMC)',
      profession: 'Orthopedic Surgeon',
      annualIncome: 'PKR 4.5 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 11\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Pashto / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Peshawar, Pakistan',
      familyCity: 'Peshawar',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 22,
      maxAge: 28,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-boy-7-1',
        url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #8] Waleed Sheikh
  {
    id: 'profile-boy-8',
    userId: 'user-boy-8',
    profileIdCode: 'VRM-000009',
    fullName: 'Waleed Sheikh',
    displayName: 'Waleed',
    gender: 'MALE',
    dateOfBirth: '1996-07-28T00:00:00Z',
    age: 29,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Sheikh (Siddiqui)',
    motherTongue: 'Urdu / Punjabi',
    phone: '+92 334 9900112',
    whatsappNumber: '+92 334 9900112',
    city: 'Sialkot',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Model Town',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Surgical & Sports Goods Exporter (LUMS BSc)',
    aboutMe: 'Managing Partner at ISO-certified surgical instruments export house in Sialkot. LUMS graduate. Modern yet deeply attached to family and ethical values.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    approvalStatus: 'APPROVED',
    viewCount: 89,
    likeCount: 32,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: false,
    consultantNote: undefined,
    educationCareer: {
      highestDegree: 'BSc Management Sciences (LUMS)',
      institution: 'LUMS Lahore',
      profession: 'Exporter & Manufacturer',
      annualIncome: 'PKR 7.2 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 10\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu / Punjabi',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Sialkot, Pakistan',
      familyCity: 'Sialkot',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 22,
      maxAge: 28,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-boy-8-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #9] Taimoor Abbasi
  {
    id: 'profile-boy-9',
    userId: 'user-boy-9',
    profileIdCode: 'VRM-000010',
    fullName: 'Taimoor Abbasi',
    displayName: 'Taimoor',
    gender: 'MALE',
    dateOfBirth: '1998-10-11T00:00:00Z',
    age: 27,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Ahle-Hadith',
    caste: 'Abbasi',
    motherTongue: 'Hindko / Urdu',
    phone: '+92 312 3322110',
    whatsappNumber: '+92 312 3322110',
    city: 'Abbottabad',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Cantt',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Assistant Commissioner (PAS / CSS Officer - QAU)',
    aboutMe: 'Civil Servant (Pakistan Administrative Service) allocated through CSS. MPhil from QAU Islamabad. Seeking a righteous, graceful, and educated life companion.',
    completionPercentage: 85,
    isFeatured: false,
    isBoosted: false,
    approvalStatus: 'APPROVED',
    viewCount: 97,
    likeCount: 35,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: false,
    consultantNote: undefined,
    educationCareer: {
      highestDegree: 'MPhil Public Policy (QAU), CSS (PAS)',
      institution: 'Quaid-i-Azam University Islamabad (QAU)',
      profession: 'Assistant Commissioner / Civil Servant',
      annualIncome: 'PKR 3.2 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 11\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Hindko / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Abbottabad, Pakistan',
      familyCity: 'Abbottabad',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 22,
      maxAge: 28,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-boy-9-1',
        url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #10] Danyal Memon
  {
    id: 'profile-boy-10',
    userId: 'user-boy-10',
    profileIdCode: 'VRM-000011',
    fullName: 'Danyal Memon',
    displayName: 'Danyal',
    gender: 'MALE',
    dateOfBirth: '1997-04-03T00:00:00Z',
    age: 28,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Memon',
    motherTongue: 'Sindhi / Memoni / Urdu',
    phone: '+92 300 4433221',
    whatsappNumber: '+92 300 4433221',
    city: 'Karachi',
    state: 'Punjab',
    province: 'Punjab',
    area: 'PECHS',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Fintech Product Lead (GIKI Alum) | Tech Entrepreneur',
    aboutMe: 'Product Lead at a leading digital bank in Karachi. GIKI engineering graduate. Modern mindset with strong respect for Memon traditions and cultural harmony.',
    completionPercentage: 92,
    isFeatured: false,
    isBoosted: false,
    approvalStatus: 'APPROVED',
    viewCount: 105,
    likeCount: 38,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: false,
    consultantNote: undefined,
    educationCareer: {
      highestDegree: 'BS Computer Systems Engg (GIKI)',
      institution: 'GIK Institute of Engineering Sciences and Technology',
      profession: 'Fintech Product Lead',
      annualIncome: 'PKR 4.5 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 9\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Sindhi / Memoni / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Karachi, Pakistan',
      familyCity: 'Karachi',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 22,
      maxAge: 28,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-boy-10-1',
        url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #1] Amna Khan
  {
    id: 'profile-amna',
    userId: 'user-amna',
    profileIdCode: 'VRM-000012',
    fullName: 'Amna Khan',
    displayName: 'Amna',
    gender: 'FEMALE',
    dateOfBirth: '2000-05-18T00:00:00Z',
    age: 25,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Khan (Yousafzai)',
    motherTongue: 'Urdu',
    phone: '+92 300 1234567',
    whatsappNumber: '+92 300 1234567',
    city: 'Lahore',
    state: 'Punjab',
    province: 'Punjab',
    area: 'DHA Phase 5',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Senior Clinical Psychologist (MSc King Edward Medical University)',
    aboutMe: 'Clinical Psychologist practicing in DHA Lahore. Compassionate, grounded in religious principles, family-oriented. Enjoys reading, creative interior arts, and community service.',
    completionPercentage: 83,
    isFeatured: true,
    isBoosted: true,
    approvalStatus: 'APPROVED',
    viewCount: 33,
    likeCount: 11,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: true,
    assignedConsultantId: 'consultant-1',
    consultantRecommended: true,
    consultantNote: 'Clinical Psychologist & Lecturer with exceptional family standing in Gulberg III, Lahore.',
    educationCareer: {
      highestDegree: 'MSc Clinical Psychology, MS Child Psychology',
      institution: 'King Edward Medical University (KEMU)',
      profession: 'Clinical Psychologist',
      annualIncome: 'PKR 2.8 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 5\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Lahore, Pakistan',
      familyCity: 'Lahore',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 27,
      maxAge: 33,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-amna-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #2] Dr. Zainab Qureshi
  {
    id: 'profile-girl-2',
    userId: 'user-girl-2',
    profileIdCode: 'VRM-000013',
    fullName: 'Dr. Zainab Qureshi',
    displayName: 'Dr.',
    gender: 'FEMALE',
    dateOfBirth: '1999-08-24T00:00:00Z',
    age: 26,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Qureshi / Syed',
    motherTongue: 'Urdu',
    phone: '+92 333 1122445',
    whatsappNumber: '+92 333 1122445',
    city: 'Islamabad',
    state: 'Punjab',
    province: 'Punjab',
    area: 'G-11',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Resident Medical Officer (MBBS Shifa International Hospital)',
    aboutMe: 'MBBS Doctor at Shifa International Hospital Islamabad. Preparing for FCPS Part 2. Soft-spoken, religious, family-oriented. Looking for a doctor, civil servant, or corporate professional.',
    completionPercentage: 80,
    isFeatured: true,
    isBoosted: true,
    approvalStatus: 'APPROVED',
    viewCount: 41,
    likeCount: 14,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: true,
    consultantNote: undefined,
    educationCareer: {
      highestDegree: 'MBBS (Shifa College of Medicine)',
      institution: 'Shifa Tameer-e-Millat University',
      profession: 'Resident Medical Officer',
      annualIncome: 'PKR 2.4 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 6\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Islamabad, Pakistan',
      familyCity: 'Islamabad',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 27,
      maxAge: 33,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-girl-2-1',
        url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #3] Fatima Zahra Kazmi
  {
    id: 'profile-girl-3',
    userId: 'user-girl-3',
    profileIdCode: 'VRM-000014',
    fullName: 'Fatima Zahra Kazmi',
    displayName: 'Fatima',
    gender: 'FEMALE',
    dateOfBirth: '2001-02-14T00:00:00Z',
    age: 24,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Shia',
    caste: 'Syed (Kazmi)',
    motherTongue: 'Urdu',
    phone: '+92 321 9988776',
    whatsappNumber: '+92 321 9988776',
    city: 'Lahore',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Model Town',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Software Engineer & UI Lead (LUMS CS Alum)',
    aboutMe: 'LUMS Computer Science graduate working as Senior UI/UX Engineer at a Silicon Valley startup remote office. Practicing Shia Syed family with high academic values.',
    completionPercentage: 84,
    isFeatured: true,
    isBoosted: false,
    approvalStatus: 'APPROVED',
    viewCount: 49,
    likeCount: 17,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: false,
    consultantNote: undefined,
    educationCareer: {
      highestDegree: 'BSc Computer Science (LUMS)',
      institution: 'LUMS Lahore',
      profession: 'Software Engineer & UI Lead',
      annualIncome: 'PKR 3.6 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 4\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Lahore, Pakistan',
      familyCity: 'Lahore',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 27,
      maxAge: 33,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-girl-3-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #4] Areeba Rajput
  {
    id: 'profile-girl-4',
    userId: 'user-girl-4',
    profileIdCode: 'VRM-000015',
    fullName: 'Areeba Rajput',
    displayName: 'Areeba',
    gender: 'FEMALE',
    dateOfBirth: '1999-11-09T00:00:00Z',
    age: 26,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Rajput',
    motherTongue: 'Urdu / Punjabi',
    phone: '+92 301 7766554',
    whatsappNumber: '+92 301 7766554',
    city: 'Rawalpindi',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Chaklala',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Senior Corporate Lawyer (LLM Queen Mary University of London)',
    aboutMe: 'Corporate & Commercial Associate at a top tier Islamabad law firm. LLM from London. Passionate about law, balanced lifestyle, and cultural harmony.',
    completionPercentage: 83,
    isFeatured: true,
    isBoosted: false,
    approvalStatus: 'APPROVED',
    viewCount: 57,
    likeCount: 20,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: false,
    consultantNote: undefined,
    educationCareer: {
      highestDegree: 'LLB (Hons), LLM Commercial Law (London)',
      institution: 'Queen Mary University of London',
      profession: 'Senior Corporate Lawyer',
      annualIncome: 'PKR 3.2 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 6\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu / Punjabi',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Rawalpindi, Pakistan',
      familyCity: 'Rawalpindi',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 27,
      maxAge: 33,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-girl-4-1',
        url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #5] Mariam Arain
  {
    id: 'profile-girl-5',
    userId: 'user-girl-5',
    profileIdCode: 'VRM-000016',
    fullName: 'Mariam Arain',
    displayName: 'Mariam',
    gender: 'FEMALE',
    dateOfBirth: '2000-09-12T00:00:00Z',
    age: 25,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Arain',
    motherTongue: 'Punjabi / Urdu',
    phone: '+92 300 8877665',
    whatsappNumber: '+92 300 8877665',
    city: 'Faisalabad',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Peoples Col',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Lecturer of English Literature (MPhil GCUF)',
    aboutMe: 'Lecturer at Govt College for Women Faisalabad. MPhil English Literature with distinction. Elegant, gentle, respectful of elders and traditional family values.',
    completionPercentage: 88,
    isFeatured: false,
    isBoosted: false,
    approvalStatus: 'APPROVED',
    viewCount: 65,
    likeCount: 23,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: false,
    consultantNote: undefined,
    educationCareer: {
      highestDegree: 'BS & MPhil English Literature (Gold Medalist)',
      institution: 'GC University Faisalabad',
      profession: 'Lecturer in English',
      annualIncome: 'PKR 1.8 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 4\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Punjabi / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Faisalabad, Pakistan',
      familyCity: 'Faisalabad',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 27,
      maxAge: 33,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-girl-5-1',
        url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #6] Hira Siddiqui
  {
    id: 'profile-girl-6',
    userId: 'user-girl-6',
    profileIdCode: 'VRM-000017',
    fullName: 'Hira Siddiqui',
    displayName: 'Hira',
    gender: 'FEMALE',
    dateOfBirth: '1998-05-30T00:00:00Z',
    age: 27,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Sheikh (Siddiqui)',
    motherTongue: 'Urdu',
    phone: '+92 334 2233445',
    whatsappNumber: '+92 334 2233445',
    city: 'Karachi',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Gulshan-e-Iqbal',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Audit Manager & ACCA Member (Big 4 Pakistan)',
    aboutMe: 'Audit Manager at leading international accounting firm in Karachi. Member of ACCA UK. Well-mannered, family-oriented, balancing career and home values.',
    completionPercentage: 90,
    isFeatured: false,
    isBoosted: false,
    approvalStatus: 'APPROVED',
    viewCount: 73,
    likeCount: 26,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: false,
    consultantNote: undefined,
    educationCareer: {
      highestDegree: 'ACCA Member, BSc Applied Accounting (Oxford Brookes)',
      institution: 'ACCA UK & Oxford Brookes University',
      profession: 'Audit Manager (Chartered Certified Accountant)',
      annualIncome: 'PKR 3.0 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 5\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Karachi, Pakistan',
      familyCity: 'Karachi',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 27,
      maxAge: 33,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-girl-6-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #7] Noor-ul-Ain Malik
  {
    id: 'profile-girl-7',
    userId: 'user-girl-7',
    profileIdCode: 'VRM-000018',
    fullName: 'Noor-ul-Ain Malik',
    displayName: 'Noor-ul-Ain',
    gender: 'FEMALE',
    dateOfBirth: '2001-08-05T00:00:00Z',
    age: 24,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Malik (Awan)',
    motherTongue: 'Saraiki / Urdu',
    phone: '+92 308 1122339',
    whatsappNumber: '+92 308 1122339',
    city: 'Multan',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Cantt',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'CSS Aspirant & Gold Medalist in Political Science (BZU)',
    aboutMe: 'Graduated top of class from BZU Multan. Currently preparing for Civil Services Examinations (CSS). Calm, pious, deeply rooted in family and moral values.',
    completionPercentage: 81,
    isFeatured: false,
    isBoosted: false,
    approvalStatus: 'APPROVED',
    viewCount: 81,
    likeCount: 29,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: false,
    consultantNote: undefined,
    educationCareer: {
      highestDegree: 'BS Political Science & International Relations (Gold Medalist)',
      institution: 'Bahauddin Zakariya University Multan',
      profession: 'CSS Aspirant & Academic Researcher',
      annualIncome: 'PKR 1.5 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 5\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Saraiki / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Multan, Pakistan',
      familyCity: 'Multan',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 27,
      maxAge: 33,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-girl-7-1',
        url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #8] Ayesha Butt
  {
    id: 'profile-girl-8',
    userId: 'user-girl-8',
    profileIdCode: 'VRM-000019',
    fullName: 'Ayesha Butt',
    displayName: 'Ayesha',
    gender: 'FEMALE',
    dateOfBirth: '1999-04-16T00:00:00Z',
    age: 26,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Butt (Kashmiri)',
    motherTongue: 'Urdu / Punjabi',
    phone: '+92 323 4455667',
    whatsappNumber: '+92 323 4455667',
    city: 'Lahore',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Johar Town',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Senior Clinical Nutritionist & Dietitian (MPhil UVAS)',
    aboutMe: 'Clinical Nutritionist at a premier private hospital in Lahore. MPhil from UVAS. Caring, enthusiastic, culinary hobbyist with strong family ethics.',
    completionPercentage: 92,
    isFeatured: false,
    isBoosted: false,
    approvalStatus: 'APPROVED',
    viewCount: 89,
    likeCount: 32,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: false,
    consultantNote: undefined,
    educationCareer: {
      highestDegree: 'MPhil Food and Clinical Nutrition',
      institution: 'University of Veterinary and Animal Sciences (UVAS Lahore)',
      profession: 'Clinical Nutritionist',
      annualIncome: 'PKR 2.2 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 5\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu / Punjabi',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Lahore, Pakistan',
      familyCity: 'Lahore',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 27,
      maxAge: 33,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-girl-8-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #9] Dr. Mahnoor Gujjar
  {
    id: 'profile-girl-9',
    userId: 'user-girl-9',
    profileIdCode: 'VRM-000020',
    fullName: 'Dr. Mahnoor Gujjar',
    displayName: 'Dr.',
    gender: 'FEMALE',
    dateOfBirth: '1998-12-01T00:00:00Z',
    age: 27,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Gujjar (Chaudhry)',
    motherTongue: 'Punjabi / Urdu',
    phone: '+92 300 9988112',
    whatsappNumber: '+92 300 9988112',
    city: 'Gujrat',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Court Road',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Dental Surgeon (BDS, RDS de\'Montmorency College of Dentistry)',
    aboutMe: 'Dental Surgeon at DHQ Teaching Hospital Gujrat. Graduate of de\'Montmorency Lahore. Dignified, polite, and devoted to family and clinical excellence.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    approvalStatus: 'APPROVED',
    viewCount: 97,
    likeCount: 35,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: false,
    consultantNote: undefined,
    educationCareer: {
      highestDegree: 'BDS (Dental Surgery), RDS PMDC Verified',
      institution: 'de\'Montmorency College of Dentistry Lahore',
      profession: 'Dental Surgeon',
      annualIncome: 'PKR 2.6 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 5\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Punjabi / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Gujrat, Pakistan',
      familyCity: 'Gujrat',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 27,
      maxAge: 33,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-girl-9-1',
        url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #10] Sara Abbasi
  {
    id: 'profile-girl-10',
    userId: 'user-girl-10',
    profileIdCode: 'VRM-000021',
    fullName: 'Sara Abbasi',
    displayName: 'Sara',
    gender: 'FEMALE',
    dateOfBirth: '2000-06-20T00:00:00Z',
    age: 25,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Ahle-Hadith',
    caste: 'Abbasi',
    motherTongue: 'Urdu / Hindko',
    phone: '+92 313 7788990',
    whatsappNumber: '+92 313 7788990',
    city: 'Islamabad',
    state: 'Punjab',
    province: 'Punjab',
    area: 'I-8',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    nationality: 'Pakistani',
    bioHeadline: 'Interior Architect & 3D Visualizer (NCA Lahore Alum)',
    aboutMe: 'B.Arch from National College of Arts (NCA). Senior Architect at a leading design firm in Islamabad. Respects religious principles, artistic lifestyle, and strong home culture.',
    completionPercentage: 87,
    isFeatured: false,
    isBoosted: false,
    approvalStatus: 'APPROVED',
    viewCount: 105,
    likeCount: 38,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'APPROVED',
    isWhatsappVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isVIPVerified: false,
    assignedConsultantId: undefined,
    consultantRecommended: false,
    consultantNote: undefined,
    educationCareer: {
      highestDegree: 'Bachelor of Architecture (B.Arch NCA)',
      institution: 'National College of Arts (NCA Lahore)',
      profession: 'Interior Architect & 3D Visualizer',
      annualIncome: 'PKR 2.5 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 5\"",
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu / Hindko',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Senior Executive / Civil Officer',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Islamabad, Pakistan',
      familyCity: 'Islamabad',
      aboutFamily: 'Cultured family with strong Islamic morals and educated background.',
    },
    partnerPreferences: {
      minAge: 27,
      maxAge: 33,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere life partner from an honorable family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showPhone: true,
      showWhatsapp: true,
      showEmail: false,
      showAge: true,
      showIncome: true,
      profileVisibility: 'PUBLIC',
    },
    photos: [
      {
        id: 'photo-profile-girl-10-1',
        url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
];


// ============================================================================
// 3. CONNECTION-BASED PACKAGES (Section 2)
// ============================================================================
export const INITIAL_PLANS: SubscriptionPlan[] = [
  {
    id: 'plan-basic',
    name: 'Basic Package',
    slug: 'BASIC',
    price: 2000,
    monthlyPrice: 2000,
    yearlyPrice: 2000,
    currency: 'PKR',
    connectionsLimit: 30,
    hasConsultant: false,
    durationMonths: 12,
    description: 'Essential matrimonial connections for genuine rishta discovery.',
    features: [
      '30 Direct Matrimonial Connection Credits',
      'Unique VRM Profile ID & Verification',
      'Full Contact Unlock (Phone, WhatsApp, Email)',
      'Unlimited Incoming Interest Requests',
      'Advanced Filters: Caste, City, Sect, Education',
      'Bank Transfer & Instant Manual Approval',
    ],
    limits: {
      connectionsCount: 30,
      directContactAccess: true,
      canChat: true,
      isFeatured: false,
      dedicatedConsultant: false,
    },
    popular: false,
  },
  {
    id: 'plan-premium',
    name: 'Premium Package',
    slug: 'PREMIUM',
    price: 5000,
    monthlyPrice: 5000,
    yearlyPrice: 5000,
    currency: 'PKR',
    connectionsLimit: 100,
    hasConsultant: false,
    durationMonths: 12,
    description: 'High-volume rishta connections with priority match recommendations.',
    features: [
      '100 Direct Matrimonial Connection Credits',
      'Highlighted Profile in Search & Compatibility Engine',
      'Direct Phone & WhatsApp Unlock on Acceptance',
      'Priority Admin Approval for Identity Documents',
      'WhatsApp & Email Notification Alerts',
      'Lifetime Connection Rollover (No Monthly Expiry)',
    ],
    limits: {
      connectionsCount: 100,
      directContactAccess: true,
      canChat: true,
      isFeatured: true,
      dedicatedConsultant: false,
    },
    popular: true,
  },
  {
    id: 'plan-vip',
    name: 'VIP Royal Package',
    slug: 'VIP',
    badge: '👑 Royal Concierge',
    price: 10000,
    monthlyPrice: 10000,
    yearlyPrice: 10000,
    currency: 'PKR',
    connectionsLimit: 300,
    hasConsultant: true,
    durationMonths: 12,
    description: 'Exclusive 1-on-1 concierge with Dedicated Senior Family Consultant.',
    features: [
      '300 Direct Matrimonial Connection Credits',
      'Dedicated Senior Family Consultant Assigned',
      'Handpicked Doctor / Bureaucrat / Corporate Rishtas',
      'Consultant Personalized Match Recommendations',
      '100% Confidential Family Background Verification',
      'Direct Family Introduction & Meeting Coordination',
      'VIP Verified Profile Badge on Dossier',
    ],
    limits: {
      connectionsCount: 300,
      directContactAccess: true,
      canChat: true,
      isFeatured: true,
      dedicatedConsultant: true,
    },
    popular: false,
  },
];

// Alias for backwards compatibility
export const INITIAL_SUBSCRIPTION_PLANS = INITIAL_PLANS;

// Additional Connection Packs (Section 38)
export const EXTRA_CONNECTION_PACKS: ExtraConnectionPack[] = [
  { id: 'pack-10', name: '10 Extra Connections', connectionsCount: 10, pricePKR: 800, description: 'Top up your account with 10 instant connections' },
  { id: 'pack-30', name: '30 Extra Connections', connectionsCount: 30, pricePKR: 2000, description: 'Popular booster pack for active matchmaking', popular: true },
  { id: 'pack-50', name: '50 Extra Connections', connectionsCount: 50, pricePKR: 3200, description: 'Extensive outreach pack for families' },
  { id: 'pack-100', name: '100 Extra Connections', connectionsCount: 100, pricePKR: 5500, description: 'Maximum volume booster for royal search' },
];

// Dedicated Senior Family Consultants (Sections 24-27)
export const INITIAL_CONSULTANTS: Consultant[] = [
  {
    id: 'consultant-1',
    name: 'Begum Bilquis Khan',
    title: 'Senior Family Matchmaker & Matrimonial Consultant',
    email: 'bilquis.khan@viproyalmatchmaking.com',
    phone: '+92 301 8899001',
    whatsappNumber: '+92 301 8899001',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    bio: 'Over 18 years of specialized experience in discreet family introductions for elite Pakistani business houses, civil servants, and medical professionals.',
    specialization: 'Doctors, Civil Servants & Corporate Executives',
    assignedClientIds: ['user-amna', 'user-ladi'],
    isActive: true,
    rating: 4.9,
    consultationsCompleted: 340,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    workingHours: '10:00 AM - 7:00 PM PKT',
  },
  {
    id: 'consultant-2',
    name: 'Dr. Tariq Mansoor',
    title: 'Director of Family Affairs & Relationship Counselor',
    email: 'tariq.mansoor@viproyalmatchmaking.com',
    phone: '+92 302 7788990',
    whatsappNumber: '+92 302 7788990',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=400',
    bio: 'Former university dean and family mediation specialist. Guides parents and candidates through cultural compatibility and background verification.',
    specialization: 'Overseas Pakistani Families & Academic Rishtas',
    assignedClientIds: ['user-boy-2'],
    isActive: true,
    rating: 4.8,
    consultationsCompleted: 215,
    availableDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    workingHours: '11:00 AM - 8:00 PM PKT',
  },
];

// Connection Transactions Log (Section 82)
export const INITIAL_CONNECTION_TRANSACTIONS: ConnectionTransaction[] = [
  {
    id: 'ctx-001',
    userId: 'user-amna',
    userProfileIdCode: 'VRM-000012',
    connectedUserId: 'user-boy-1',
    connectedProfileId: 'profile-boy-1',
    connectedProfileIdCode: 'VRM-000002',
    creditsUsed: 1,
    reason: 'Contact Details Unlocked',
    date: '2025-02-15T14:30:00Z',
  },
];

// Clean Real-Time Activity Stores
export const INITIAL_INTERESTS: InterestRequest[] = [
  {
    id: 'interest-sample-1',
    senderId: 'user-boy-1',
    senderName: 'Dr. Hamza Malik',
    senderPhoto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    senderProfileId: 'profile-boy-1',
    senderProfileIdCode: 'VRM-000002',
    receiverId: 'user-amna',
    receiverName: 'Amna Khan',
    receiverPhoto: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    receiverProfileId: 'profile-amna',
    receiverProfileIdCode: 'VRM-000012',
    status: 'ACCEPTED',
    message: 'Salam, our family was very impressed by your academic credentials and values.',
    createdAt: '2025-02-14T10:00:00Z',
    updatedAt: '2025-02-15T14:30:00Z',
    relationshipStatus: 'FAMILY_CONTACTED',
  }
];

export const INITIAL_FAVORITES: FavoriteItem[] = [];
export const INITIAL_CONVERSATIONS: Conversation[] = [];
export const INITIAL_MESSAGES: Record<string, ChatMessage[]> = {};
export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'user-amna',
    type: 'CONSULTANT_RECOMMENDATION',
    title: 'Consultant Recommendation',
    description: 'Senior Consultant Begum Bilquis Khan recommended Dr. Hamza Malik for your dossier.',
    linkUrl: '/dashboard/connections',
    isRead: false,
    createdAt: '2025-02-15T12:00:00Z',
  }
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-001',
    invoiceNumber: 'INV-2025-001',
    userId: 'user-amna',
    userProfileIdCode: 'VRM-000012',
    userName: 'Amna Khan',
    planName: 'VIP Royal Package (300 Connections)',
    amount: 10000,
    subtotal: 10000,
    taxAmount: 0,
    discountAmount: 0,
    currency: 'PKR',
    status: 'PAID',
    paymentMethod: 'Bank Transfer (Meezan Bank)',
    transactionId: 'TRX-MEEZ-883921',
    date: '2025-02-01T12:00:00Z',
  }
];

export const INITIAL_VERIFICATIONS: VerificationRequest[] = [];
export const INITIAL_REPORTS: AbuseReport[] = [];

export const INITIAL_TICKETS: SupportTicket[] = [
  {
    id: 'ticket-001',
    ticketCode: 'SUP-000123',
    userId: 'user-amna',
    userName: 'Amna Khan',
    userEmail: 'amna.khan@gmail.com',
    userProfileIdCode: 'VRM-000012',
    subject: 'Consultant introduction meeting schedule inquiry',
    category: 'CONSULTANT',
    relatedProfileId: 'VRM-000002',
    priority: 'NORMAL',
    status: 'OPEN',
    createdAt: '2025-02-16T11:00:00Z',
    updatedAt: '2025-02-16T11:00:00Z',
    messages: [
      {
        id: 'msg-t-1',
        sender: 'USER',
        senderName: 'Amna Khan',
        text: 'Assalam o Alaikum, we would like to coordinate a phone consultation with Begum Bilquis Khan regarding the proposal for Dr. Hamza Malik (VRM-000002).',
        timestamp: '2025-02-16T11:00:00Z',
      }
    ]
  }
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coupon-vip20',
    code: 'VIP20',
    discountPercent: 20,
    expiresAt: '2026-12-31T23:59:59Z',
    usageLimit: 500,
    timesUsed: 14,
    applicablePackages: ['BASIC', 'PREMIUM', 'VIP'],
    isActive: true,
  }
];

export const INITIAL_CMS: CMSContent = {
  announcementBanner: {
    enabled: true,
    text: 'VIP Royal Matchmaking – Exclusive Connections with Dedicated Family Consultants',
    link: '/pricing',
  },
  successStories: [
    {
      id: 'story-1',
      coupleName: 'Dr. Zaid & Fatima',
      weddingDate: 'December 2024',
      story: 'Through VIP Royal Matchmaking and Senior Consultant Begum Bilquis Khan, both our families were connected with complete transparency and respect. Highly recommended for families seeking dignified matchmaking.',
      photoUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=800',
      city: 'Islamabad & Lahore',
      isApproved: true,
    },
    {
      id: 'story-2',
      coupleName: 'Engr. Shahmeer & Dr. Ayla',
      weddingDate: 'January 2025',
      story: 'The connection credits model gave us complete control over our outreach. The privacy safeguards and verified backgrounds made our parents feel completely secure.',
      photoUrl: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&q=80&w=800',
      city: 'Karachi (PECHS)',
      isApproved: true,
    }
  ],
  faqs: [
    {
      question: 'What is a connection credit and when is it deducted?',
      answer: 'A connection credit allows you to unlock verified direct contact details (phone, WhatsApp, email) or establish a confirmed mutual match. Merely viewing profiles or candidate dossiers never deducts connection credits.',
      category: 'Connections',
    },
    {
      question: 'Do connection credits expire every month?',
      answer: 'No. Connection credits do not expire monthly. Your purchased credits remain safely in your account as long as your account is in good standing.',
      category: 'Connections',
    },
    {
      question: 'Can I purchase additional connections without changing my package?',
      answer: 'Yes, you can purchase booster packs of 10, 30, 50, or 100 connections anytime from your dashboard.',
      category: 'Billing',
    },
    {
      question: 'What is the role of a Dedicated Senior Family Consultant?',
      answer: 'For VIP Royal members, a Senior Consultant reviews your family requirements, handpicks compatible matches, performs confidential background verifications, and assists in arranging family introduction meetings.',
      category: 'Consultant',
    },
    {
      question: 'How does bank transfer payment approval work?',
      answer: 'After transferring funds to our official bank account, submit your transaction ID and receipt screenshot. Our administrative desk verifies the payment and activates your connection credits promptly.',
      category: 'Billing',
    }
  ],
  testimonials: [],
};

export const INITIAL_AUDIT_LOGS: AdminAuditLog[] = [
  {
    id: 'audit-001',
    adminId: 'user-ladi',
    adminName: 'Ladi (Super Admin)',
    action: 'SYSTEM_UPGRADE_INITIALIZED',
    targetType: 'SETTING',
    targetId: 'VRM-SYSTEM',
    ipAddress: '127.0.0.1',
    timestamp: '2025-02-01T00:00:00Z',
    details: 'VIP Royal Matchmaking connection-based architecture activated with verified profile IDs.',
  }
];

export const INITIAL_PAYMENT_PROOFS: PaymentProof[] = [
  {
    id: 'proof-001',
    userId: 'user-amna',
    userName: 'Amna Khan',
    userEmail: 'amna.khan@gmail.com',
    userPhone: '+92 300 9988776',
    userProfileIdCode: 'VRM-000012',
    planSlug: 'VIP',
    planName: 'VIP Royal Package (300 Connections)',
    connectionsAdded: 300,
    amount: 10000,
    currency: 'PKR',
    paymentMethod: 'BANK_TRANSFER',
    senderBank: 'Meezan Bank Ltd',
    senderName: 'Amna Khan',
    senderMobileNumber: '+92 300 9988776',
    transactionId: 'TRX-MEEZ-883921',
    transactionDate: '2025-02-01',
    screenshotUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=800',
    status: 'APPROVED',
    submittedAt: '2025-02-01T11:45:00Z',
    reviewedAt: '2025-02-01T12:00:00Z',
    reviewedBy: 'Super Admin Ladi',
  }
];

export const INITIAL_RECEIVING_ACCOUNTS: ReceivingAccount[] = [
  {
    id: 'bank-meezan-1',
    provider: 'BANK_TRANSFER',
    bankName: 'Meezan Bank Ltd (Islamic Banking)',
    accountTitle: 'VIP ROYAL MATCHMAKING PVT LTD',
    accountNumber: '02010108928371',
    iban: 'PK45MEZN0002010108928371',
    branchName: 'Main Boulevard Gulberg Branch, Lahore',
    instructions: 'Please transfer the exact package amount via online banking, ATM, or Raast. Attach transaction ID and proof screenshot for expedited approval.',
    isActive: true,
    isPrimary: true,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'bank-faysal-2',
    provider: 'BANK_TRANSFER',
    bankName: 'Faysal Bank Islamic',
    accountTitle: 'VIP ROYAL MATCHMAKING SERVICES',
    accountNumber: '30098712345678',
    iban: 'PK89FAYS3009871234567801',
    branchName: 'DHA Phase 5 Branch, Lahore',
    instructions: 'Direct bank transfer or mobile app funds transfer accepted.',
    isActive: true,
    isPrimary: false,
    createdAt: '2025-01-01T00:00:00Z',
  }
];

export const INITIAL_SETTINGS: SystemSettings = {
  siteName: 'VIP Royal Matchmaking',
  tagline: 'Pakistan’s Premier Connection-Based Matrimonial Platform',
  contactEmail: 'concierge@viproyalmatchmaking.com',
  supportPhone: '+92 300 1234567',
  profileIdPrefix: 'VRM-',
  minAge: 20,
  requireEmailVerification: true,
  requireWhatsAppVerification: true,
  requireAdminProfileApproval: true,
  freeTierConnectionsLimit: 5,
  whatsappNotificationsEnabled: true,
  emailNotificationsEnabled: true,
  tax: {
    taxEnabled: false,
    taxPercentage: 5,
    taxFixed: 0,
    taxLabel: 'Service Fee / Tax (5%)',
  },
  matchingWeights: {
    ageWeight: 10,
    locationWeight: 10,
    educationWeight: 10,
    professionWeight: 10,
    lifestyleWeight: 10,
    familyWeight: 10,
    maritalWeight: 10,
  },
  maintenanceMode: false,
  allowNewRegistrations: true,
  whatsappSupportNumber: '+92 300 1234567',
  supportEmail: 'support@viproyalmatchmaking.com',
  currency: 'PKR',
};

