import {
  User,
  MatrimonialProfile,
  InterestRequest,
  FavoriteItem,
  Conversation,
  ChatMessage,
  NotificationItem,
  SubscriptionPlan,
  Invoice,
  VerificationRequest,
  AbuseReport,
  SupportTicket,
  Coupon,
  CMSContent,
  AdminAuditLog,
  SystemSettings,
  PaymentProof,
  ReceivingAccount,
} from './types';

// ============================================================================
// 1. SYSTEM USERS (1 Super Admin + 10 Boys + 10 Girls = 21 Real Users)
// ============================================================================
export const INITIAL_USERS: User[] = [
  // SUPER ADMIN
  {
    id: 'user-ladi',
    name: 'Ladi (Super Admin)',
    email: 'ladi02893@gmail.com',
    role: 'SUPER_ADMIN',
    subscriptionTier: 'PREMIUM_PLUS',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-01-01T00:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-ladi',
  },
  // [MALE #1] Dr. Hamza Malik
  {
    id: 'user-boy-1',
    name: 'Dr. Hamza Malik',
    email: 'hamza.malik@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-1',
  },
  // [MALE #2] Engr. Bilal Ahmed
  {
    id: 'user-boy-2',
    name: 'Engr. Bilal Ahmed',
    email: 'bilal.ahmed@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-2',
  },
  // [MALE #3] Usman Tariq
  {
    id: 'user-boy-3',
    name: 'Usman Tariq',
    email: 'usman.tariq@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-3',
  },
  // [MALE #4] Ali Raza Kazmi
  {
    id: 'user-boy-4',
    name: 'Ali Raza Kazmi',
    email: 'ali.raza@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-4',
  },
  // [MALE #5] Shahzad Arain
  {
    id: 'user-boy-5',
    name: 'Shahzad Arain',
    email: 'shahzad.arain@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-5',
  },
  // [MALE #6] Farhan Cheema
  {
    id: 'user-boy-6',
    name: 'Farhan Cheema',
    email: 'farhan.cheema@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-6',
  },
  // [MALE #7] Dr. Hassan Niazi
  {
    id: 'user-boy-7',
    name: 'Dr. Hassan Niazi',
    email: 'hassan.niazi@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-7',
  },
  // [MALE #8] Waleed Sheikh
  {
    id: 'user-boy-8',
    name: 'Waleed Sheikh',
    email: 'waleed.sheikh@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-8',
  },
  // [MALE #9] Taimoor Abbasi
  {
    id: 'user-boy-9',
    name: 'Taimoor Abbasi',
    email: 'taimoor.abbasi@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-9',
  },
  // [MALE #10] Danyal Memon
  {
    id: 'user-boy-10',
    name: 'Danyal Memon',
    email: 'danyal.memon@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-10',
  },
  // [FEMALE #1] Amna Khan
  {
    id: 'user-amna',
    name: 'Amna Khan',
    email: 'amna.khan@gmail.com',
    role: 'USER',
    subscriptionTier: 'PREMIUM_PLUS',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-amna',
  },
  // [FEMALE #2] Dr. Zainab Qureshi
  {
    id: 'user-girl-2',
    name: 'Dr. Zainab Qureshi',
    email: 'zainab.qureshi@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-2',
  },
  // [FEMALE #3] Fatima Zahra Kazmi
  {
    id: 'user-girl-3',
    name: 'Fatima Zahra Kazmi',
    email: 'fatima.zahra@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-3',
  },
  // [FEMALE #4] Areeba Rajput
  {
    id: 'user-girl-4',
    name: 'Areeba Rajput',
    email: 'areeba.rajput@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-4',
  },
  // [FEMALE #5] Mariam Arain
  {
    id: 'user-girl-5',
    name: 'Mariam Arain',
    email: 'mariam.arain@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-5',
  },
  // [FEMALE #6] Hira Siddiqui
  {
    id: 'user-girl-6',
    name: 'Hira Siddiqui',
    email: 'hira.siddiqui@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-6',
  },
  // [FEMALE #7] Noor-ul-Ain Malik
  {
    id: 'user-girl-7',
    name: 'Noor-ul-Ain Malik',
    email: 'noor.malik@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-7',
  },
  // [FEMALE #8] Ayesha Butt
  {
    id: 'user-girl-8',
    name: 'Ayesha Butt',
    email: 'ayesha.butt@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-8',
  },
  // [FEMALE #9] Dr. Mahnoor Gujjar
  {
    id: 'user-girl-9',
    name: 'Dr. Mahnoor Gujjar',
    email: 'mahnoor.gujjar@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-9',
  },
  // [FEMALE #10] Sara Abbasi
  {
    id: 'user-girl-10',
    name: 'Sara Abbasi',
    email: 'sara.abbasi@gmail.com',
    role: 'USER',
    subscriptionTier: 'FREE',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-girl-10',
  },
];

// ============================================================================
// 2. MATRIMONIAL PROFILES (1 Super Admin + 10 Boys + 10 Girls = 21 Profiles)
// ============================================================================
export const INITIAL_PROFILES: MatrimonialProfile[] = [
  // SUPER ADMIN PROFILE
  {
    id: 'profile-ladi',
    userId: 'user-ladi',
    fullName: 'Ladi (Super Admin)',
    displayName: 'Ladi',
    gender: 'MALE',
    dateOfBirth: '1995-05-15',
    age: 30,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Syed',
    motherTongue: 'Urdu',
    phone: '+92 300 1234567',
    city: 'Lahore',
    state: 'Punjab',
    province: 'Punjab',
    area: 'DHA Phase 5',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Super Administrator & Matchmaking Executive Director',
    aboutMe: 'Official System Administrator for Compatible Matrimonials. Dedicated to ensuring trust, privacy, and authentic rishta connections.',
    completionPercentage: 100,
    isFeatured: true,
    isBoosted: true,
    viewCount: 120,
    likeCount: 45,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: "Master's in Computer Science",
      institution: 'LUMS Lahore',
      profession: 'Executive Director & Tech Architect',
      annualIncome: 'PKR 10 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 10\"",
      weight: '74 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu',
      languagesSpoken: ['English', 'Urdu', 'Punjabi'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Retired Civil Servant',
      motherOccupation: 'Educator & Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Lahore, Pakistan',
      aboutFamily: 'Respected, educated family with high ethical standards.',
    },
    partnerPreferences: {
      minAge: 22,
      maxAge: 30,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking a sincere, educated life partner with good moral values.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-ladi-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #1] Dr. Hamza Malik
  {
    id: 'profile-boy-1',
    userId: 'user-boy-1',
    fullName: 'Dr. Hamza Malik',
    displayName: 'Dr.',
    gender: 'MALE',
    dateOfBirth: '1996-04-12',
    age: 29,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Malik',
    motherTongue: 'Punjabi / Urdu',
    phone: '+92 300 1122334',
    city: 'Lahore',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Gulberg III',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Cardiologist (FCPS) at Punjab Institute of Cardiology (PIC)',
    aboutMe: 'Practicing Cardiologist at PIC Lahore. Balance religious ethics with professional medical career. Looking for an educated, family-oriented partner with similar values.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 29,
    likeCount: 10,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'MBBS, FCPS Cardiology',
      institution: 'King Edward Medical University (KEMU)',
      profession: 'Cardiologist',
      annualIncome: 'PKR 4.2 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 11\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Punjabi / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'JOINT',
      familyValues: 'MODERATE_RELIGIOUS',
      fatherOccupation: 'Retired Bureaucrat (Govt of Punjab)',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 2,
      familyLocation: 'Gulberg III, Lahore',
      aboutFamily: 'Malik family with high academic and moral values residing in Lahore.',
    },
    partnerPreferences: {
      minAge: 23,
      maxAge: 28,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Bachelors or Higher (Doctor / Engineer / Professional preferred)',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-boy-1-1',
        url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #2] Engr. Bilal Ahmed
  {
    id: 'profile-boy-2',
    userId: 'user-boy-2',
    fullName: 'Engr. Bilal Ahmed',
    displayName: 'Engr.',
    gender: 'MALE',
    dateOfBirth: '1997-06-15',
    age: 28,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Syed',
    motherTongue: 'Urdu',
    phone: '+92 301 4455667',
    city: 'Islamabad',
    state: 'Punjab',
    province: 'Punjab',
    area: 'F-10',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Principal AI/Cloud Architect (NUST) | Tech Consultant',
    aboutMe: 'Lead AI Engineer at a US-based cloud consultancy. NUST graduate with a passion for tech, fitness, and family life. Seeking a compatible, caring life partner.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 33,
    likeCount: 12,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'MS Computer Science & AI',
      institution: 'NUST Islamabad',
      profession: 'Principal AI/Cloud Architect',
      annualIncome: 'PKR 5.5 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 12\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE_RELIGIOUS',
      fatherOccupation: 'Executive Engineer (WAPDA)',
      motherOccupation: 'Associate Professor',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'F-10/2, Islamabad',
      aboutFamily: 'Syed family with high academic and moral values residing in Islamabad.',
    },
    partnerPreferences: {
      minAge: 22,
      maxAge: 27,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Bachelors / Masters',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-boy-2-1',
        url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #3] Usman Tariq
  {
    id: 'profile-boy-3',
    userId: 'user-boy-3',
    fullName: 'Usman Tariq',
    displayName: 'Usman',
    gender: 'MALE',
    dateOfBirth: '1995-09-22',
    age: 30,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Rajput',
    motherTongue: 'Urdu / Punjabi',
    phone: '+92 321 8899001',
    city: 'Karachi',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Clifton',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Senior Investment Banker (CFA / IBA Karachi)',
    aboutMe: 'Vice President of M&A and Investment Banking at a leading financial institution in Karachi. IBA alumnus, CFA charterholder. Seeking a graceful, intelligent partner.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 37,
    likeCount: 14,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'BBA & MBA Finance (IBA), CFA',
      institution: 'Institute of Business Administration (IBA Karachi)',
      profession: 'Senior Investment Banker',
      annualIncome: 'PKR 6.0 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 10\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu / Punjabi',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE_TRADITIONAL',
      fatherOccupation: 'Managing Director (Logistics Co)',
      motherOccupation: 'Homemaker',
      brothersCount: 2,
      sistersCount: 0,
      familyLocation: 'Block 4, Clifton, Karachi',
      aboutFamily: 'Rajput family with high academic and moral values residing in Karachi.',
    },
    partnerPreferences: {
      minAge: 24,
      maxAge: 29,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Graduation / Masters',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-boy-3-1',
        url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #4] Ali Raza Kazmi
  {
    id: 'profile-boy-4',
    userId: 'user-boy-4',
    fullName: 'Ali Raza Kazmi',
    displayName: 'Ali',
    gender: 'MALE',
    dateOfBirth: '1998-03-10',
    age: 27,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Shia',
    caste: 'Syed (Kazmi)',
    motherTongue: 'Urdu',
    phone: '+92 333 5566778',
    city: 'Rawalpindi',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Bahria Ph 4',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Chartered Accountant (ACA / LUMS) | Senior Auditor',
    aboutMe: 'Chartered Accountant working with Big 4 Audit Firm. LUMS graduate. High regard for family values, faith, and mutual respect in marriage.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 41,
    likeCount: 16,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'BSc Accounting & Finance (LUMS), ACA',
      institution: 'LUMS & ICAP',
      profession: 'Chartered Accountant',
      annualIncome: 'PKR 3.8 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 9\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'JOINT',
      familyValues: 'RELIGIOUS_MODERN',
      fatherOccupation: 'Civil Judge (Retd)',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 2,
      familyLocation: 'Bahria Town Phase 4, Rawalpindi',
      aboutFamily: 'Syed (Kazmi) family with high academic and moral values residing in Rawalpindi.',
    },
    partnerPreferences: {
      minAge: 21,
      maxAge: 26,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Bachelors or Masters',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-boy-4-1',
        url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #5] Shahzad Arain
  {
    id: 'profile-boy-5',
    userId: 'user-boy-5',
    fullName: 'Shahzad Arain',
    displayName: 'Shahzad',
    gender: 'MALE',
    dateOfBirth: '1994-11-05',
    age: 31,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Arain',
    motherTongue: 'Punjabi / Urdu',
    phone: '+92 300 7788990',
    city: 'Faisalabad',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Civil Lines',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Textile Export Director (FAST-NUCES & UK Graduate)',
    aboutMe: 'Director at an established textile export manufacturing firm in Faisalabad. Educated, well-travelled, grounded in family values. Looking for a polite, graceful partner.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 45,
    likeCount: 18,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'BS Industrial Engg (FAST), MSc Supply Chain (UK)',
      institution: 'FAST-NUCES & University of Manchester',
      profession: 'Textile Export Director',
      annualIncome: 'PKR 9.5 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "6' 0\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Punjabi / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'JOINT',
      familyValues: 'TRADITIONAL_AFFLUENT',
      fatherOccupation: 'Industrialist & Chairman',
      motherOccupation: 'Homemaker',
      brothersCount: 2,
      sistersCount: 1,
      familyLocation: 'Civil Lines, Faisalabad',
      aboutFamily: 'Arain family with high academic and moral values residing in Faisalabad.',
    },
    partnerPreferences: {
      minAge: 23,
      maxAge: 28,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Bachelors / Masters',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-boy-5-1',
        url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #6] Farhan Cheema
  {
    id: 'profile-boy-6',
    userId: 'user-boy-6',
    fullName: 'Farhan Cheema',
    displayName: 'Farhan',
    gender: 'MALE',
    dateOfBirth: '1997-08-19',
    age: 28,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Jatt (Cheema)',
    motherTongue: 'Punjabi / Urdu',
    phone: '+92 322 3344556',
    city: 'Gujranwala',
    state: 'Punjab',
    province: 'Punjab',
    area: 'DC Colony',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Civil Engineer & Construction Contractor (UET Lahore)',
    aboutMe: 'Civil Engineer running family infrastructure construction firm. UET Lahore graduate. Active sportsman, respects family traditions and Islamic values.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 49,
    likeCount: 20,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'BSc Civil Engineering (UET Lahore)',
      institution: 'UET Lahore',
      profession: 'Civil Engineer & Contractor',
      annualIncome: 'PKR 4.8 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "6' 1\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Punjabi / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'JOINT',
      familyValues: 'MODERATE_RELIGIOUS',
      fatherOccupation: 'Landowner & Govt Contractor',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 2,
      familyLocation: 'DC Colony, Gujranwala',
      aboutFamily: 'Jatt (Cheema) family with high academic and moral values residing in Gujranwala.',
    },
    partnerPreferences: {
      minAge: 22,
      maxAge: 27,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Graduate / Medical / Engineering / Teaching',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-boy-6-1',
        url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #7] Dr. Hassan Niazi
  {
    id: 'profile-boy-7',
    userId: 'user-boy-7',
    fullName: 'Dr. Hassan Niazi',
    displayName: 'Dr.',
    gender: 'MALE',
    dateOfBirth: '1993-12-14',
    age: 32,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Niazi (Pathan)',
    motherTongue: 'Pashto / Urdu',
    phone: '+92 345 6677889',
    city: 'Peshawar',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Hayatabad',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Orthopedic Surgeon (MBBS, MS Ortho) at HMC Peshawar',
    aboutMe: 'Orthopedic Surgeon at Hayatabad Medical Complex. Humble, dedicated, family-centric. Looking for an educated partner from a respected family.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 53,
    likeCount: 22,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'MBBS, MS Orthopedic Surgery',
      institution: 'Khyber Medical College (KMC)',
      profession: 'Orthopedic Surgeon',
      annualIncome: 'PKR 4.5 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 11\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Pashto / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'JOINT',
      familyValues: 'TRADITIONAL_PASHTUN',
      fatherOccupation: 'Professor of Surgery (Retd)',
      motherOccupation: 'Homemaker',
      brothersCount: 2,
      sistersCount: 1,
      familyLocation: 'Phase 2, Hayatabad, Peshawar',
      aboutFamily: 'Niazi (Pathan) family with high academic and moral values residing in Peshawar.',
    },
    partnerPreferences: {
      minAge: 23,
      maxAge: 29,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Doctor (MBBS/BDS) or Master Degree',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-boy-7-1',
        url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #8] Waleed Sheikh
  {
    id: 'profile-boy-8',
    userId: 'user-boy-8',
    fullName: 'Waleed Sheikh',
    displayName: 'Waleed',
    gender: 'MALE',
    dateOfBirth: '1996-07-28',
    age: 29,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Sheikh (Siddiqui)',
    motherTongue: 'Urdu / Punjabi',
    phone: '+92 334 9900112',
    city: 'Sialkot',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Model Town',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Surgical & Sports Goods Exporter (LUMS BSc)',
    aboutMe: 'Managing Partner at ISO-certified surgical instruments export house in Sialkot. LUMS graduate. Modern yet deeply attached to family and ethical values.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 57,
    likeCount: 24,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'BSc Management Sciences (LUMS)',
      institution: 'LUMS Lahore',
      profession: 'Exporter & Manufacturer',
      annualIncome: 'PKR 7.2 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 10\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu / Punjabi',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'JOINT',
      familyValues: 'MODERATE_RELIGIOUS',
      fatherOccupation: 'Export House Chairman',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 2,
      familyLocation: 'Model Town, Sialkot',
      aboutFamily: 'Sheikh (Siddiqui) family with high academic and moral values residing in Sialkot.',
    },
    partnerPreferences: {
      minAge: 22,
      maxAge: 27,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Graduation / Masters',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-boy-8-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #9] Taimoor Abbasi
  {
    id: 'profile-boy-9',
    userId: 'user-boy-9',
    fullName: 'Taimoor Abbasi',
    displayName: 'Taimoor',
    gender: 'MALE',
    dateOfBirth: '1998-10-11',
    age: 27,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Ahle-Hadith',
    caste: 'Abbasi',
    motherTongue: 'Hindko / Urdu',
    phone: '+92 312 3322110',
    city: 'Abbottabad',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Cantt',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Assistant Commissioner (PAS / CSS Officer - QAU)',
    aboutMe: 'Civil Servant (Pakistan Administrative Service) allocated through CSS. MPhil from QAU Islamabad. Seeking a righteous, graceful, and educated life companion.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 61,
    likeCount: 26,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'MPhil Public Policy (QAU), CSS (PAS)',
      institution: 'Quaid-i-Azam University Islamabad (QAU)',
      profession: 'Assistant Commissioner / Civil Servant',
      annualIncome: 'PKR 3.2 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 11\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Hindko / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'RELIGIOUS_EDUCATED',
      fatherOccupation: 'Brigadier (Retd), Pak Army',
      motherOccupation: 'Senior Educationist',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Cantt, Abbottabad',
      aboutFamily: 'Abbasi family with high academic and moral values residing in Abbottabad.',
    },
    partnerPreferences: {
      minAge: 21,
      maxAge: 26,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Masters / Graduation',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-boy-9-1',
        url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [MALE #10] Danyal Memon
  {
    id: 'profile-boy-10',
    userId: 'user-boy-10',
    fullName: 'Danyal Memon',
    displayName: 'Danyal',
    gender: 'MALE',
    dateOfBirth: '1997-04-03',
    age: 28,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Memon',
    motherTongue: 'Sindhi / Memoni / Urdu',
    phone: '+92 300 4433221',
    city: 'Karachi',
    state: 'Punjab',
    province: 'Punjab',
    area: 'PECHS',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Fintech Product Lead (GIKI Alum) | Tech Entrepreneur',
    aboutMe: 'Product Lead at a leading digital bank in Karachi. GIKI engineering graduate. Modern mindset with strong respect for Memon traditions and cultural harmony.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 65,
    likeCount: 28,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'BS Computer Systems Engg (GIKI)',
      institution: 'GIK Institute of Engineering Sciences and Technology',
      profession: 'Fintech Product Lead',
      annualIncome: 'PKR 4.5 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 9\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Sindhi / Memoni / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'JOINT',
      familyValues: 'MODERATE_TRADITIONAL',
      fatherOccupation: 'Wholesale Commodity Merchant',
      motherOccupation: 'Homemaker',
      brothersCount: 2,
      sistersCount: 1,
      familyLocation: 'Block 2, PECHS, Karachi',
      aboutFamily: 'Memon family with high academic and moral values residing in Karachi.',
    },
    partnerPreferences: {
      minAge: 22,
      maxAge: 27,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Graduation / Masters',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-boy-10-1',
        url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #1] Amna Khan
  {
    id: 'profile-amna',
    userId: 'user-amna',
    fullName: 'Amna Khan',
    displayName: 'Amna',
    gender: 'FEMALE',
    dateOfBirth: '2000-05-18',
    age: 25,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Khan (Yousafzai)',
    motherTongue: 'Urdu',
    phone: '+92 300 1234567',
    city: 'Lahore',
    state: 'Punjab',
    province: 'Punjab',
    area: 'DHA Phase 5',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Senior Clinical Psychologist (MSc King Edward Medical University)',
    aboutMe: 'Clinical Psychologist practicing in DHA Lahore. Compassionate, grounded in religious principles, family-oriented. Enjoys reading, creative interior arts, and community service.',
    completionPercentage: 95,
    isFeatured: true,
    isBoosted: true,
    viewCount: 29,
    likeCount: 10,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'MSc Clinical Psychology, MS Child Psychology',
      institution: 'King Edward Medical University (KEMU)',
      profession: 'Clinical Psychologist',
      annualIncome: 'PKR 2.8 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 5\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE_RELIGIOUS',
      fatherOccupation: 'Executive Vice President (Habib Bank Ltd)',
      motherOccupation: 'Senior School Principal (Beaconhouse)',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Sector C, DHA Phase 5, Lahore',
      aboutFamily: 'Khan (Yousafzai) family with high academic and moral values residing in Lahore.',
    },
    partnerPreferences: {
      minAge: 27,
      maxAge: 32,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Masters or Higher (Doctor / Engineer / CSP / Business Owner)',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-amna-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #2] Dr. Zainab Qureshi
  {
    id: 'profile-girl-2',
    userId: 'user-girl-2',
    fullName: 'Dr. Zainab Qureshi',
    displayName: 'Dr.',
    gender: 'FEMALE',
    dateOfBirth: '1999-08-24',
    age: 26,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Qureshi / Syed',
    motherTongue: 'Urdu',
    phone: '+92 333 1122445',
    city: 'Islamabad',
    state: 'Punjab',
    province: 'Punjab',
    area: 'G-11',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Resident Medical Officer (MBBS Shifa International Hospital)',
    aboutMe: 'MBBS Doctor at Shifa International Hospital Islamabad. Preparing for FCPS Part 2. Soft-spoken, religious, family-oriented. Looking for a doctor, civil servant, or corporate professional.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 33,
    likeCount: 12,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'MBBS (Shifa College of Medicine)',
      institution: 'Shifa Tameer-e-Millat University',
      profession: 'Resident Medical Officer',
      annualIncome: 'PKR 2.4 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 6\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'RELIGIOUS_EDUCATED',
      fatherOccupation: 'Federal Secretary (Retd)',
      motherOccupation: 'Associate Professor of Botany',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'G-11/3, Islamabad',
      aboutFamily: 'Qureshi / Syed family with high academic and moral values residing in Islamabad.',
    },
    partnerPreferences: {
      minAge: 27,
      maxAge: 32,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. MBBS / FCPS / Engg / CSP / Masters',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-girl-2-1',
        url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #3] Fatima Zahra Kazmi
  {
    id: 'profile-girl-3',
    userId: 'user-girl-3',
    fullName: 'Fatima Zahra Kazmi',
    displayName: 'Fatima',
    gender: 'FEMALE',
    dateOfBirth: '2001-02-14',
    age: 24,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Shia',
    caste: 'Syed (Kazmi)',
    motherTongue: 'Urdu',
    phone: '+92 321 9988776',
    city: 'Lahore',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Model Town',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Software Engineer & UI Lead (LUMS CS Alum)',
    aboutMe: 'LUMS Computer Science graduate working as Senior UI/UX Engineer at a Silicon Valley startup remote office. Practicing Shia Syed family with high academic values.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 37,
    likeCount: 14,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'BSc Computer Science (LUMS)',
      institution: 'LUMS Lahore',
      profession: 'Software Engineer & UI Lead',
      annualIncome: 'PKR 3.6 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 4\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'RELIGIOUS_MODERN',
      fatherOccupation: 'Senior Advocate Supreme Court',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Block C, Model Town, Lahore',
      aboutFamily: 'Syed (Kazmi) family with high academic and moral values residing in Lahore.',
    },
    partnerPreferences: {
      minAge: 26,
      maxAge: 31,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Graduation / Masters (IT / Finance / Engineering / Medical)',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-girl-3-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #4] Areeba Rajput
  {
    id: 'profile-girl-4',
    userId: 'user-girl-4',
    fullName: 'Areeba Rajput',
    displayName: 'Areeba',
    gender: 'FEMALE',
    dateOfBirth: '1999-11-09',
    age: 26,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Rajput',
    motherTongue: 'Urdu / Punjabi',
    phone: '+92 301 7766554',
    city: 'Rawalpindi',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Chaklala',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Senior Corporate Lawyer (LLM Queen Mary University of London)',
    aboutMe: 'Corporate & Commercial Associate at a top tier Islamabad law firm. LLM from London. Passionate about law, balanced lifestyle, and cultural harmony.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 41,
    likeCount: 16,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'LLB (Hons), LLM Commercial Law (London)',
      institution: 'Queen Mary University of London',
      profession: 'Senior Corporate Lawyer',
      annualIncome: 'PKR 3.2 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 6\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu / Punjabi',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE_EDUCATED',
      fatherOccupation: 'Major General (Retd), Pak Army',
      motherOccupation: 'Homemaker',
      brothersCount: 2,
      sistersCount: 0,
      familyLocation: 'Chaklala Scheme 3, Rawalpindi',
      aboutFamily: 'Rajput family with high academic and moral values residing in Rawalpindi.',
    },
    partnerPreferences: {
      minAge: 27,
      maxAge: 32,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Masters / Professional (Army Officer / CSS / Lawyer / Engineer)',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-girl-4-1',
        url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #5] Mariam Arain
  {
    id: 'profile-girl-5',
    userId: 'user-girl-5',
    fullName: 'Mariam Arain',
    displayName: 'Mariam',
    gender: 'FEMALE',
    dateOfBirth: '2000-09-12',
    age: 25,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Arain',
    motherTongue: 'Punjabi / Urdu',
    phone: '+92 300 8877665',
    city: 'Faisalabad',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Peoples Col',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Lecturer of English Literature (MPhil GCUF)',
    aboutMe: 'Lecturer at Govt College for Women Faisalabad. MPhil English Literature with distinction. Elegant, gentle, respectful of elders and traditional family values.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 45,
    likeCount: 18,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'BS & MPhil English Literature (Gold Medalist)',
      institution: 'GC University Faisalabad',
      profession: 'Lecturer in English',
      annualIncome: 'PKR 1.8 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 4\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Punjabi / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'JOINT',
      familyValues: 'MODERATE_RELIGIOUS',
      fatherOccupation: 'Landowner & Agriculturalist',
      motherOccupation: 'Homemaker',
      brothersCount: 2,
      sistersCount: 1,
      familyLocation: 'Peoples Colony No. 1, Faisalabad',
      aboutFamily: 'Arain family with high academic and moral values residing in Faisalabad.',
    },
    partnerPreferences: {
      minAge: 27,
      maxAge: 31,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Bachelors / Masters / Civil Service / Business',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-girl-5-1',
        url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #6] Hira Siddiqui
  {
    id: 'profile-girl-6',
    userId: 'user-girl-6',
    fullName: 'Hira Siddiqui',
    displayName: 'Hira',
    gender: 'FEMALE',
    dateOfBirth: '1998-05-30',
    age: 27,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Sheikh (Siddiqui)',
    motherTongue: 'Urdu',
    phone: '+92 334 2233445',
    city: 'Karachi',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Gulshan-e-Iqbal',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Audit Manager & ACCA Member (Big 4 Pakistan)',
    aboutMe: 'Audit Manager at leading international accounting firm in Karachi. Member of ACCA UK. Well-mannered, family-oriented, balancing career and home values.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 49,
    likeCount: 20,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'ACCA Member, BSc Applied Accounting (Oxford Brookes)',
      institution: 'ACCA UK & Oxford Brookes University',
      profession: 'Audit Manager (Chartered Certified Accountant)',
      annualIncome: 'PKR 3.0 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 5\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE_EDUCATED',
      fatherOccupation: 'Chartered Accountant (Partner Retd)',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 2,
      familyLocation: 'Block 6, Gulshan-e-Iqbal, Karachi',
      aboutFamily: 'Sheikh (Siddiqui) family with high academic and moral values residing in Karachi.',
    },
    partnerPreferences: {
      minAge: 28,
      maxAge: 33,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Chartered Accountant / MBA / Engineering / Medical',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-girl-6-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #7] Noor-ul-Ain Malik
  {
    id: 'profile-girl-7',
    userId: 'user-girl-7',
    fullName: 'Noor-ul-Ain Malik',
    displayName: 'Noor-ul-Ain',
    gender: 'FEMALE',
    dateOfBirth: '2001-08-05',
    age: 24,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Malik (Awan)',
    motherTongue: 'Saraiki / Urdu',
    phone: '+92 308 1122339',
    city: 'Multan',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Cantt',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'CSS Aspirant & Gold Medalist in Political Science (BZU)',
    aboutMe: 'Graduated top of class from BZU Multan. Currently preparing for Civil Services Examinations (CSS). Calm, pious, deeply rooted in family and moral values.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 53,
    likeCount: 22,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'BS Political Science & International Relations (Gold Medalist)',
      institution: 'Bahauddin Zakariya University Multan',
      profession: 'CSS Aspirant & Academic Researcher',
      annualIncome: 'PKR 1.5 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 5\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Saraiki / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'JOINT',
      familyValues: 'MODERATE_RELIGIOUS',
      fatherOccupation: 'Executive Engineer (Irrigation Dept)',
      motherOccupation: 'Homemaker',
      brothersCount: 2,
      sistersCount: 0,
      familyLocation: 'Officers Colony, Cantt, Multan',
      aboutFamily: 'Malik (Awan) family with high academic and moral values residing in Multan.',
    },
    partnerPreferences: {
      minAge: 26,
      maxAge: 31,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. CSP / Civil Service / Doctor / Engineer / Masters',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-girl-7-1',
        url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #8] Ayesha Butt
  {
    id: 'profile-girl-8',
    userId: 'user-girl-8',
    fullName: 'Ayesha Butt',
    displayName: 'Ayesha',
    gender: 'FEMALE',
    dateOfBirth: '1999-04-16',
    age: 26,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Butt (Kashmiri)',
    motherTongue: 'Urdu / Punjabi',
    phone: '+92 323 4455667',
    city: 'Lahore',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Johar Town',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Senior Clinical Nutritionist & Dietitian (MPhil UVAS)',
    aboutMe: 'Clinical Nutritionist at a premier private hospital in Lahore. MPhil from UVAS. Caring, enthusiastic, culinary hobbyist with strong family ethics.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 57,
    likeCount: 24,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'MPhil Food and Clinical Nutrition',
      institution: 'University of Veterinary and Animal Sciences (UVAS Lahore)',
      profession: 'Clinical Nutritionist',
      annualIncome: 'PKR 2.2 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 5\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu / Punjabi',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE_RELIGIOUS',
      fatherOccupation: 'Wholesale Electronics Distributor',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 2,
      familyLocation: 'Block F, Johar Town, Lahore',
      aboutFamily: 'Butt (Kashmiri) family with high academic and moral values residing in Lahore.',
    },
    partnerPreferences: {
      minAge: 27,
      maxAge: 32,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Bachelors / Masters / Business',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-girl-8-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #9] Dr. Mahnoor Gujjar
  {
    id: 'profile-girl-9',
    userId: 'user-girl-9',
    fullName: 'Dr. Mahnoor Gujjar',
    displayName: 'Dr.',
    gender: 'FEMALE',
    dateOfBirth: '1998-12-01',
    age: 27,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Gujjar (Chaudhry)',
    motherTongue: 'Punjabi / Urdu',
    phone: '+92 300 9988112',
    city: 'Gujrat',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Court Road',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Dental Surgeon (BDS, RDS de\'Montmorency College of Dentistry)',
    aboutMe: 'Dental Surgeon at DHQ Teaching Hospital Gujrat. Graduate of de\'Montmorency Lahore. Dignified, polite, and devoted to family and clinical excellence.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 61,
    likeCount: 26,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'BDS (Dental Surgery), RDS PMDC Verified',
      institution: 'de\'Montmorency College of Dentistry Lahore',
      profession: 'Dental Surgeon',
      annualIncome: 'PKR 2.6 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 5\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Punjabi / Urdu',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'JOINT',
      familyValues: 'MODERATE_RELIGIOUS',
      fatherOccupation: 'Senior Civil Judge (Retd)',
      motherOccupation: 'Homemaker',
      brothersCount: 2,
      sistersCount: 1,
      familyLocation: 'Court Road, Gujrat',
      aboutFamily: 'Gujjar (Chaudhry) family with high academic and moral values residing in Gujrat.',
    },
    partnerPreferences: {
      minAge: 28,
      maxAge: 33,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Doctor (MBBS/FCPS) / Civil Servant / Engineer',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-girl-9-1',
        url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
  // [FEMALE #10] Sara Abbasi
  {
    id: 'profile-girl-10',
    userId: 'user-girl-10',
    fullName: 'Sara Abbasi',
    displayName: 'Sara',
    gender: 'FEMALE',
    dateOfBirth: '2000-06-20',
    age: 25,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Ahle-Hadith',
    caste: 'Abbasi',
    motherTongue: 'Urdu / Hindko',
    phone: '+92 313 7788990',
    city: 'Islamabad',
    state: 'Punjab',
    province: 'Punjab',
    area: 'I-8',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Interior Architect & 3D Visualizer (NCA Lahore Alum)',
    aboutMe: 'B.Arch from National College of Arts (NCA). Senior Architect at a leading design firm in Islamabad. Respects religious principles, artistic lifestyle, and strong home culture.',
    completionPercentage: 95,
    isFeatured: false,
    isBoosted: false,
    viewCount: 65,
    likeCount: 28,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    verificationBadge: 'GOVERNMENT_ID',
    educationCareer: {
      highestDegree: 'Bachelor of Architecture (B.Arch NCA)',
      institution: 'National College of Arts (NCA Lahore)',
      profession: 'Interior Architect & 3D Visualizer',
      annualIncome: 'PKR 2.5 Million',
      currency: 'PKR',
    },
    lifestyle: {
      height: "5' 5\"",
      weight: '68 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu / Hindko',
      languagesSpoken: ['English', 'Urdu'],
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'RELIGIOUS_EDUCATED',
      fatherOccupation: 'Director General (Retd), CDA',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Sector I-8/2, Islamabad',
      aboutFamily: 'Abbasi family with high academic and moral values residing in Islamabad.',
    },
    partnerPreferences: {
      minAge: 27,
      maxAge: 32,
      maritalStatuses: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      expectationsNotes: 'Seeking an educated, sincere partner from a respectable family. Masters / Graduation (Engineer / Architect / IT / Civil Servant)',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
    },
    photos: [
      {
        id: 'photo-profile-girl-10-1',
        url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
        isPrimary: true,
        isApproved: true,
      },
    ],
  },
];


// ============================================================================
// 3. MEMBERSHIP PLANS
// ============================================================================
export const INITIAL_PLANS: SubscriptionPlan[] = [
  {
    id: 'plan-basic',
    name: 'Free Basic Matchmaking',
    slug: 'FREE',
    price: 0,
    monthlyPrice: 0,
    durationMonths: 12,
    description: 'Essential rishta discovery for genuine Pakistani families.',
    features: [
      'Create and manage verified matrimonial profile',
      'Browse all candidates across Pakistan & overseas',
      'Send up to 2 direct interest requests monthly',
      'Standard photo and bio visibility',
      'Basic search filters (City, Caste, Sect, Age)',
    ],
    limits: {
      monthlyInterests: 2,
      viewProfileLimit: 20,
      canChat: false,
      directContactAccess: false,
      isFeatured: false,
    },
    popular: false,
  },
  {
    id: 'plan-premium',
    name: 'Elite Executive Plan',
    slug: 'PREMIUM',
    price: 12000,
    monthlyPrice: 12000,
    durationMonths: 1,
    description: 'Active matchmaking with direct chat & full contact details.',
    features: [
      'Unlimited interest requests & instant approvals',
      'Direct WhatsApp & phone contact reveal upon match',
      'Real-time encrypted direct chat messaging',
      'Profile boosted on search & recommendation engine',
      'Dedicated matchmaker support on WhatsApp',
    ],
    limits: {
      monthlyInterests: 50,
      viewProfileLimit: 200,
      canChat: true,
      directContactAccess: true,
      isFeatured: true,
    },
    popular: true,
  },
  {
    id: 'plan-vip',
    name: 'VIP Royal Matchmaking',
    slug: 'PREMIUM_PLUS',
    price: 35000,
    monthlyPrice: 35000,
    durationMonths: 3,
    description: 'Exclusive 1-on-1 personalized matchmaking concierge by senior consultants.',
    features: [
      'Dedicated Senior Family Consultant assigned',
      'Handpicked high-profile doctor / bureaucrat / corporate rishtas',
      '100% confidential private family background checks',
      'Direct introduction meetings arranged',
      'Top priority verified badge & lifetime validity option',
    ],
    limits: {
      monthlyInterests: 999,
      viewProfileLimit: 999,
      canChat: true,
      directContactAccess: true,
      isFeatured: true,
    },
    popular: false,
  },
];

// Clean Real-Time Activity Stores
export const INITIAL_INTERESTS: InterestRequest[] = [];
export const INITIAL_FAVORITES: FavoriteItem[] = [];
export const INITIAL_CONVERSATIONS: Conversation[] = [];
export const INITIAL_MESSAGES: ChatMessage[] = [];
export const INITIAL_NOTIFICATIONS: NotificationItem[] = [];
export const INITIAL_INVOICES: Invoice[] = [];
export const INITIAL_VERIFICATIONS: VerificationRequest[] = [];
export const INITIAL_REPORTS: AbuseReport[] = [];
export const INITIAL_SUPPORT_TICKETS: SupportTicket[] = [];
export const INITIAL_COUPONS: Coupon[] = [];
export const INITIAL_CMS: CMSContent[] = [];
export const INITIAL_AUDIT_LOGS: AdminAuditLog[] = [];
export const INITIAL_PAYMENT_PROOFS: PaymentProof[] = [];
export const INITIAL_RECEIVING_ACCOUNTS: ReceivingAccount[] = [];

export const INITIAL_SETTINGS: SystemSettings = {
  maintenanceMode: false,
  requireVerificationForContact: true,
  freeTierMonthlyInterestLimit: 2,
  allowNewRegistrations: true,
  whatsappSupportNumber: '+92 300 1234567',
  supportEmail: 'support@compatiblematrimonials.pk',
  currency: 'PKR',
};
