import {
  User,
  MatrimonialProfile,
  InterestRequest,
  FavoriteItem,
  Conversation,
  ChatMessage,
  NotificationItem,
  SubscriptionPlan,
  Invoice,
  VerificationRequest,
  AbuseReport,
  SupportTicket,
  Coupon,
  CMSContent,
  AdminAuditLog,
  SystemSettings,
  PaymentProof,
  ReceivingAccount,
} from './types';

// ============================================================================
// 1. SYSTEM USERS (Super Admin + Candidate Bride + Candidate Groom = 3 Users)
// ============================================================================
export const INITIAL_USERS: User[] = [
  // SUPER ADMIN
  {
    id: 'user-ladi',
    name: 'Ladi (Super Admin)',
    email: 'ladi02893@gmail.com',
    role: 'SUPER_ADMIN',
    subscriptionTier: 'PREMIUM_PLUS',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-01-01T00:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-ladi',
  },

  // 1. AMNA KHAN (CANDIDATE BRIDE)
  {
    id: 'user-amna',
    name: 'Amna Khan',
    email: 'amna.khan@gmail.com',
    role: 'USER',
    subscriptionTier: 'PREMIUM_PLUS',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-01T10:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-amna',
  },

  // 2. DR. HAMZA MALIK (CANDIDATE GROOM)
  {
    id: 'user-boy-1',
    name: 'Dr. Hamza Malik',
    email: 'hamza.malik@gmail.com',
    role: 'USER',
    subscriptionTier: 'PREMIUM',
    accountStatus: 'ACTIVE',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    createdAt: '2025-02-02T11:00:00Z',
    lastActive: 'Online',
    profileId: 'profile-boy-1',
  },
];

// ============================================================================
// 2. MATRIMONIAL PROFILES (Super Admin + Amna Khan + Dr. Hamza Malik = 3 Profiles)
// ============================================================================
export const INITIAL_PROFILES: MatrimonialProfile[] = [
  // SUPER ADMIN PROFILE
  {
    id: 'profile-ladi',
    userId: 'user-ladi',
    fullName: 'Ladi (Super Admin)',
    displayName: 'Ladi',
    gender: 'MALE',
    dateOfBirth: '1995-05-15',
    age: 30,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Syed',
    motherTongue: 'Urdu',
    phone: '+92 300 1234567',
    city: 'Lahore',
    state: 'Punjab',
    province: 'Punjab',
    area: 'DHA Phase 5',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Super Administrator & Matchmaking Executive Director',
    aboutMe: 'Official System Administrator for Compatible Matrimonials. Dedicated to ensuring trust, privacy, and authentic rishta connections.',
    completionPercentage: 100,
    isFeatured: true,
    isBoosted: false,
    verificationBadge: 'APPROVED',
    viewCount: 1250,
    likeCount: 95,
    fraudScore: 0,
    profileQualityScore: 100,
    aiSummary: 'Platform Super Administrator with complete system access and security oversight.',
    personalityInsights: ['Visionary', 'Analytical', 'Dedicated'],
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
    photos: [
      {
        id: 'photo-ladi-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800',
        isPrimary: true,
        isApproved: true,
        order: 1,
      },
    ],
    educationCareer: {
      highestDegree: "Master's in Computer Science",
      institution: 'LUMS Lahore',
      profession: 'Executive Director & Tech Architect',
      monthlyIncome: 'PKR 800,000+ / month',
      annualIncome: 'PKR 10 Million',
      employmentSector: 'BUSINESS',
      workingLocation: 'Lahore, Pakistan',
    },
    lifestyle: {
      height: "5 ft 10 in (178 cm)",
      weight: '74 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu',
      languagesSpoken: ['English', 'Urdu', 'Punjabi'],
      livingStatus: 'Living in Own House (Family Residence)',
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Retired Civil Servant',
      motherOccupation: 'Educator & Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Lahore, Pakistan',
      livingStatus: 'Living in Own House',
      aboutFamily: 'Respected, educated family with high ethical standards.',
    },
    partnerPreferences: {
      ageRange: { min: 22, max: 30 },
      heightRange: { min: "5 ft 2 in", max: "5 ft 8 in" },
      maritalStatus: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      sects: ['Sunni', 'Open'],
      caste: ['All Castes (No Bar)'],
      preferredLocations: ['Lahore', 'Islamabad', 'Karachi'],
      monthlyIncome: 'Open',
      expectationsNotes: 'Seeking a sincere, educated life partner with good moral values.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
      showLastSeen: true,
    },
  },

  // 1. AMNA KHAN (CANDIDATE BRIDE)
  {
    id: 'profile-amna',
    userId: 'user-amna',
    fullName: 'Amna Khan',
    displayName: 'Amna K.',
    gender: 'FEMALE',
    dateOfBirth: '1999-08-20',
    age: 25,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Niazi (Pathan)',
    subClan: 'Khan',
    motherTongue: 'Urdu',
    phone: '+92 301 2345678',
    city: 'Lahore',
    state: 'Punjab',
    province: 'Punjab',
    area: 'Gulberg III',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Clinical Psychologist with a balanced outlook towards religious values and career',
    aboutMe: 'Alhamdulillah, I am a family-oriented professional who values mutual respect, open communication, and spiritual growth. Working as a psychologist and part-time lecturer.',
    completionPercentage: 96,
    isFeatured: true,
    isBoosted: true,
    verificationBadge: 'APPROVED',
    viewCount: 480,
    likeCount: 52,
    fraudScore: 0,
    profileQualityScore: 98,
    aiSummary: 'AI Analysis: High educational compatibility in Healthcare/Psychology. Well-settled family background in Lahore.',
    personalityInsights: ['Empathetic', 'Articulate', 'Cultured'],
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-01T10:00:00Z',
    photos: [
      {
        id: 'photo-amna-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800',
        isPrimary: true,
        isApproved: true,
        order: 1,
      },
    ],
    educationCareer: {
      highestDegree: 'MS in Clinical Psychology',
      institution: 'Kinnaird College / GCU Lahore',
      profession: 'Clinical Psychologist & Lecturer',
      monthlyIncome: 'PKR 180,000 / month',
      annualIncome: 'PKR 2.2 Million',
      employmentSector: 'PRIVATE',
      workingLocation: 'Lahore, Pakistan',
    },
    lifestyle: {
      height: "5 ft 6 in (168 cm)",
      weight: '56 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu',
      languagesSpoken: ['English', 'Urdu', 'Pashto'],
      livingStatus: 'Living with Family in Own House',
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Executive Businessman',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 2,
      familyLocation: 'Gulberg, Lahore',
      livingStatus: 'Own Bungalow',
      aboutFamily: 'Warm, educated, and well-settled family with deep ethical values.',
    },
    partnerPreferences: {
      ageRange: { min: 26, max: 33 },
      heightRange: { min: "5 ft 8 in", max: "6 ft 2 in" },
      maritalStatus: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      sects: ['Sunni', 'Open'],
      caste: ['Pathan', 'Syed', 'Rajput', 'No Bar'],
      preferredLocations: ['Lahore', 'Islamabad', 'Abroad (UAE/UK)'],
      monthlyIncome: 'PKR 250,000+ / month',
      expectationsNotes: 'Seeking a sincere, well-educated, and professionally settled gentleman with kind demeanor.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
      showLastSeen: true,
    },
  },

  // 2. DR. HAMZA MALIK (CANDIDATE GROOM)
  {
    id: 'profile-boy-1',
    userId: 'user-boy-1',
    fullName: 'Dr. Hamza Malik',
    displayName: 'Dr. Hamza M.',
    gender: 'MALE',
    dateOfBirth: '1995-10-12',
    age: 29,
    maritalStatus: 'NEVER_MARRIED',
    religion: 'ISLAM',
    sectOrCommunity: 'Sunni',
    caste: 'Malik (Awan)',
    motherTongue: 'Urdu',
    phone: '+92 300 1122334',
    city: 'Lahore',
    state: 'Punjab',
    province: 'Punjab',
    area: 'DHA Phase 6',
    country: 'Pakistan',
    citizenship: 'Pakistani',
    bioHeadline: 'Consultant Cardiologist (FCPS) with strong family values',
    aboutMe: 'Specialist physician working at a premier hospital in Lahore. Grounded, family-oriented, and looking for an educated life partner.',
    completionPercentage: 98,
    isFeatured: true,
    isBoosted: true,
    verificationBadge: 'APPROVED',
    viewCount: 620,
    likeCount: 65,
    fraudScore: 0,
    profileQualityScore: 99,
    aiSummary: 'Top-tier Medical Professional. High lifestyle and income stability verified.',
    personalityInsights: ['Dedicated', 'Intellectual', 'Grounded'],
    createdAt: '2025-02-02T11:00:00Z',
    updatedAt: '2025-02-02T11:00:00Z',
    photos: [
      {
        id: 'photo-b1',
        url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=800',
        isPrimary: true,
        isApproved: true,
        order: 1,
      },
    ],
    educationCareer: {
      highestDegree: 'MBBS, FCPS Cardiology',
      institution: 'King Edward Medical University',
      profession: 'Consultant Cardiologist / Physician',
      monthlyIncome: 'PKR 450,000 / month',
      annualIncome: 'PKR 5.5 Million',
      employmentSector: 'PRIVATE',
      workingLocation: 'Lahore, Pakistan',
    },
    lifestyle: {
      height: "5 ft 11 in (180 cm)",
      weight: '76 kg',
      diet: 'HALAL_ONLY',
      smoking: 'NO',
      drinking: 'NO',
      motherTongue: 'Urdu',
      languagesSpoken: ['English', 'Urdu', 'Punjabi'],
      livingStatus: 'Living in Own House (Family Residence)',
    },
    familyInfo: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE',
      fatherOccupation: 'Professor of Medicine',
      motherOccupation: 'Doctor (Gynecologist)',
      brothersCount: 1,
      sistersCount: 1,
      familyLocation: 'Lahore, Pakistan',
      livingStatus: 'Living in Own House',
      aboutFamily: 'Medical family background with high social standing and ethical grounding.',
    },
    partnerPreferences: {
      ageRange: { min: 23, max: 29 },
      heightRange: { min: "5 ft 4 in", max: "5 ft 9 in" },
      maritalStatus: ['NEVER_MARRIED'],
      religions: ['ISLAM'],
      sects: ['Sunni', 'Open'],
      caste: ['Open / No Bar'],
      preferredLocations: ['Lahore', 'Islamabad', 'Rawalpindi'],
      monthlyIncome: 'Open',
      expectationsNotes: 'Seeking a graceful, educated lady from a noble and practicing family.',
    },
    privacy: {
      photoVisibility: 'ALL',
      contactVisibility: 'ONLY_ACCEPTED_INTERESTS',
      showAge: true,
      showIncome: true,
      showLastSeen: true,
    },
  },
];

// ============================================================================
// 3. SUBSCRIPTION PLANS
// ============================================================================
export const INITIAL_PLANS: SubscriptionPlan[] = [
  {
    id: 'plan-free',
    name: 'Standard Member',
    slug: 'FREE',
    badge: 'Free Tier',
    description: 'Basic matchmaking profile and search',
    monthlyPrice: 0,
    yearlyPrice: 0,
    currency: 'PKR',
    features: ['View public candidate profiles', 'Send up to 5 interests/month', 'Basic search filters'],
    limits: {
      monthlyInterests: 5,
      dailyDirectMessages: 0,
      canViewVisitors: false,
      hasPriorityMatching: false,
      hasFeaturedBadge: false,
      directContactAccess: false,
    },
    isActive: true,
    isPopular: false,
  },
  {
    id: 'plan-premium',
    name: 'Elite Executive',
    slug: 'PREMIUM',
    badge: 'Most Popular',
    description: 'Direct contact details and direct messaging',
    monthlyPrice: 15000,
    yearlyPrice: 150000,
    currency: 'PKR',
    features: ['View verified contact numbers', 'Unlimited Direct Messages', 'Priority profile placement', 'Verified match badge'],
    limits: {
      monthlyInterests: 50,
      dailyDirectMessages: 100,
      canViewVisitors: true,
      hasPriorityMatching: true,
      hasFeaturedBadge: true,
      directContactAccess: true,
    },
    isActive: true,
    isPopular: true,
  },
  {
    id: 'plan-vip',
    name: 'VIP Royal Matchmaking',
    slug: 'PREMIUM_PLUS',
    badge: 'VIP Elite',
    description: 'Dedicated relationship advisor and highest priority',
    monthlyPrice: 35000,
    yearlyPrice: 350000,
    currency: 'PKR',
    features: ['Dedicated relationship advisor', 'Background verification report', 'Confidential browsing', 'Highest match score boost'],
    limits: {
      monthlyInterests: 100,
      dailyDirectMessages: 500,
      canViewVisitors: true,
      hasPriorityMatching: true,
      hasFeaturedBadge: true,
      directContactAccess: true,
    },
    isActive: true,
    isPopular: false,
  },
];

// ============================================================================
// 4. REALTIME ACTIVITY & TRANSACTION COLLECTIONS (Start Clean 100% Realtime)
// ============================================================================
export const INITIAL_INTERESTS: InterestRequest[] = [];
export const INITIAL_FAVORITES: FavoriteItem[] = [];
export const INITIAL_CONVERSATIONS: Conversation[] = [];
export const INITIAL_MESSAGES: Record<string, ChatMessage[]> = {};
export const INITIAL_NOTIFICATIONS: NotificationItem[] = [];
export const INITIAL_PAYMENT_PROOFS: PaymentProof[] = [];
export const INITIAL_INVOICES: Invoice[] = [];
export const INITIAL_VERIFICATIONS: VerificationRequest[] = [];
export const INITIAL_REPORTS: AbuseReport[] = [];
export const INITIAL_TICKETS: SupportTicket[] = [];
export const INITIAL_COUPONS: Coupon[] = [];

// ============================================================================
// 5. CMS & PLATFORM SYSTEM CONFIGURATION
// ============================================================================
export const INITIAL_CMS: CMSContent = {
  announcementBanner: {
    enabled: true,
    text: 'Welcome to Compatible Matrimonials - Pakistan’s Premier AI-Powered Rishta Bureau.',
    link: '/search',
  },
  successStories: [
    {
      id: 'story-1',
      coupleName: 'Dr. Hamza & Amna',
      weddingDate: 'December 2024',
      story: 'We connected through Compatible Matrimonials AI compatibility matching. Alhamdulillah, our families bonded seamlessly.',
      photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
      city: 'Lahore',
    },
  ],
  faqs: [
    {
      question: 'How does mutual contact unlocking work?',
      answer: 'Your direct phone number and WhatsApp details remain strictly confidential. Only when both parties send and accept an interest request are phone numbers unlocked.',
      category: 'PRIVACY',
    },
  ],
  testimonials: [
    {
      name: 'Begum Salma Qureshi',
      role: 'Mother of Bride',
      location: 'Islamabad',
      rating: 5,
      quote: 'The level of privacy, verified profiles, and AI compatibility is unmatched by traditional marriage bureaus.',
      photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    },
  ],
};

export const INITIAL_AUDIT_LOGS: AdminAuditLog[] = [];

export const INITIAL_SETTINGS: SystemSettings = {
  siteName: 'Compatible Matrimonials',
  tagline: 'Where Compatibility Meets Commitment',
  contactEmail: 'concierge@compatiblematrimonials.pk',
  supportPhone: '+92 300 1234567',
  minAge: 18,
  requireEmailVerification: false,
  requireAdminProfileApproval: false,
  freeTierMonthlyInterestLimit: 5,
  matchingWeights: {
    ageWeight: 15,
    locationWeight: 15,
    educationWeight: 15,
    professionWeight: 15,
    lifestyleWeight: 15,
    familyWeight: 15,
    maritalWeight: 10,
  },
};

// ============================================================================
// 6. OFFICIAL RECEIVING ACCOUNTS (Real Pakistani Bank / Wallet Accounts)
// ============================================================================
export const INITIAL_RECEIVING_ACCOUNTS: ReceivingAccount[] = [
  {
    id: 'acc-1',
    provider: 'JAZZCASH',
    bankName: 'JazzCash Wallet / Merchant',
    accountTitle: 'Compatible Matrimonials',
    accountNumber: '0300-1234567',
    instructions: 'Send fee via JazzCash App or Retailer & attach screenshot with Trx ID.',
    isActive: true,
    isPrimary: true,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'acc-2',
    provider: 'EASYPAISA',
    bankName: 'Easypaisa Mobile Account',
    accountTitle: 'Compatible Matrimonials',
    accountNumber: '0345-8899001',
    instructions: 'Transfer fee via Easypaisa App or Telenor franchise and submit payment proof.',
    isActive: true,
    isPrimary: true,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'acc-3',
    provider: 'BANK_TRANSFER',
    bankName: 'Meezan Bank Limited',
    accountTitle: 'Compatible Matrimonials Bureau',
    accountNumber: '0101-0103456789',
    iban: 'PK36MEZN0001010103456789',
    branchName: 'DHA Phase 5 Branch, Lahore',
    instructions: 'Online Interbank Fund Transfer (IBFT) or ATM deposit.',
    isActive: true,
    isPrimary: true,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'acc-4',
    provider: 'RAAST',
    bankName: 'Raast Instant ID (State Bank of Pakistan)',
    accountTitle: 'Compatible Matrimonials',
    accountNumber: '03001234567',
    instructions: 'Instant zero-fee transfer via any Pakistani banking app using Raast ID.',
    isActive: true,
    isPrimary: false,
    createdAt: '2025-01-01T00:00:00Z',
  },
];
