// Comprehensive global countries and cities dataset for TRUEPAIR Matrimonial Bureau

export interface CountryWithCities {
  country: string;
  code: string;
  cities: string[];
}

export const COUNTRY_CITIES_MAP: Record<string, string[]> = {
  Pakistan: [
    'Lahore',
    'Karachi',
    'Islamabad',
    'Rawalpindi',
    'Faisalabad',
    'Multan',
    'Peshawar',
    'Quetta',
    'Sialkot',
    'Gujranwala',
    'Bahawalpur',
    'Sargodha',
    'Abbottabad',
    'Gujrat',
    'Mirpur (AJK)',
    'Muzaffarabad',
    'Rahim Yar Khan',
    'Jhelum',
    'Wah Cantt',
    'Hyderabad',
    'Sukkur',
    'Mardan',
    'Swat',
    'Chiniot',
    'Kasur',
    'Sheikhupura',
    'Attock',
    'Dera Ghazi Khan',
    'Sahiwal',
    'Okara',
    'Larkana',
    'Gilgit',
    'Skardu',
  ],
  'United Kingdom': [
    'London',
    'Birmingham',
    'Manchester',
    'Leeds',
    'Glasgow',
    'Liverpool',
    'Edinburgh',
    'Bristol',
    'Sheffield',
    'Bradford',
    'Cardiff',
    'Leicester',
    'Nottingham',
    'Coventry',
    'Newcastle',
    'Belfast',
    'Southampton',
    'Reading',
    'Luton',
    'Slough',
    'Milton Keynes',
    'Oxford',
    'Cambridge',
    'Aberdeen',
    'Stoke-on-Trent',
    'Wolverhampton',
    'Derby',
    'Preston',
    'Huddersfield',
  ],
  'United States': [
    'New York, NY',
    'Los Angeles, CA',
    'Chicago, IL',
    'Houston, TX',
    'Dallas, TX',
    'San Francisco, CA',
    'Austin, TX',
    'Seattle, WA',
    'Boston, MA',
    'Atlanta, GA',
    'Washington, D.C.',
    'Miami, FL',
    'Philadelphia, PA',
    'San Jose, CA',
    'San Diego, CA',
    'Phoenix, AZ',
    'Detroit, MI',
    'Minneapolis, MN',
    'Denver, CO',
    'Charlotte, NC',
    'Orlando, FL',
    'Tampa, FL',
    'Columbus, OH',
    'Indianapolis, IN',
    'Nashville, TN',
    'Jersey City, NJ',
    'Edison, NJ',
    'Plano, TX',
    'Fremont, CA',
  ],
  Canada: [
    'Toronto',
    'Vancouver',
    'Montreal',
    'Calgary',
    'Ottawa',
    'Edmonton',
    'Mississauga',
    'Brampton',
    'Winnipeg',
    'Hamilton',
    'Surrey',
    'Quebec City',
    'Markham',
    'Vaughan',
    'Kitchener',
    'Waterloo',
    'London (ON)',
    'Halifax',
    'Victoria',
    'Windsor',
    'Richmond (BC)',
    'Burnaby',
    'Oakville',
    'Milton',
  ],
  'United Arab Emirates': [
    'Dubai',
    'Abu Dhabi',
    'Sharjah',
    'Ajman',
    'Ras Al Khaimah',
    'Al Ain',
    'Fujairah',
    'Umm Al Quwain',
  ],
  'Saudi Arabia': [
    'Riyadh',
    'Jeddah',
    'Mecca',
    'Medina',
    'Dammam',
    'Khobar',
    'Dhahran',
    'Jubail',
    'Taif',
    'Tabuk',
    'Abha',
    'Yanbu',
    'Al Ahsa',
    'Najran',
  ],
  India: [
    'Mumbai',
    'Delhi NCR',
    'Bangalore',
    'Hyderabad',
    'Chennai',
    'Kolkata',
    'Ahmedabad',
    'Pune',
    'Surat',
    'Jaipur',
    'Lucknow',
    'Chandigarh',
    'Amritsar',
    'Kochi',
    'Indore',
    'Bhopal',
    'Nagpur',
    'Patna',
    'Vadodara',
    'Ludhiana',
    'Agra',
    'Varanasi',
    'Srinagar',
    'Coimbatore',
    'Visakhapatnam',
    'Guwahati',
    'Bhubaneswar',
    'Thiruvananthapuram',
  ],
  Australia: [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Canberra',
    'Gold Coast',
    'Newcastle',
    'Wollongong',
    'Hobart',
    'Geelong',
    'Darwin',
  ],
  Germany: [
    'Berlin',
    'Munich',
    'Frankfurt',
    'Hamburg',
    'Cologne',
    'Stuttgart',
    'Dusseldorf',
    'Dortmund',
    'Essen',
    'Leipzig',
    'Bremen',
    'Dresden',
    'Hanover',
    'Nuremberg',
    'Bonn',
  ],
  Qatar: [
    'Doha',
    'Al Rayyan',
    'Al Wakrah',
    'Al Khor',
    'Umm Salal',
    'Lusail',
    'Al Shamal',
  ],
  Kuwait: [
    'Kuwait City',
    'Al Ahmadi',
    'Hawalli',
    'Salmiya',
    'Al Farwaniyah',
    'Al Jahra',
    'Sabah Al Salem',
  ],
  Oman: [
    'Muscat',
    'Salalah',
    'Sohar',
    'Nizwa',
    'Sur',
    'Seeb',
    'Barka',
    'Ibri',
  ],
  Bahrain: [
    'Manama',
    'Riffa',
    'Muharraq',
    'Hamad Town',
    'A\'ali',
    'Isa Town',
    'Sitra',
    'Budaiya',
  ],
  Malaysia: [
    'Kuala Lumpur',
    'Penang (George Town)',
    'Johor Bahru',
    'Shah Alam',
    'Petaling Jaya',
    'Subang Jaya',
    'Malacca',
    'Ipoh',
    'Kuching',
    'Kota Kinabalu',
    'Putrajaya',
    'Cyberjaya',
  ],
  Singapore: [
    'Singapore (Central)',
    'Jurong',
    'Tampines',
    'Woodlands',
    'Bedok',
    'Ang Mo Kio',
  ],
  Bangladesh: [
    'Dhaka',
    'Chittagong',
    'Sylhet',
    'Rajshahi',
    'Khulna',
    'Barisal',
    'Rangpur',
    'Comilla',
    'Mymensingh',
    'Narayanganj',
    'Gazipur',
  ],
  Turkey: [
    'Istanbul',
    'Ankara',
    'Izmir',
    'Bursa',
    'Antalya',
    'Adana',
    'Konya',
    'Gaziantep',
    'Mersin',
    'Trabzon',
    'Bodrum',
  ],
  France: [
    'Paris',
    'Lyon',
    'Marseille',
    'Toulouse',
    'Nice',
    'Bordeaux',
    'Strasbourg',
    'Nantes',
    'Lille',
    'Montpellier',
    'Rennes',
  ],
  Italy: [
    'Rome',
    'Milan',
    'Naples',
    'Turin',
    'Florence',
    'Bologna',
    'Venice',
    'Genoa',
    'Palermo',
    'Verona',
    'Bari',
  ],
  Spain: [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Seville',
    'Zaragoza',
    'Malaga',
    'Murcia',
    'Palma de Mallorca',
    'Bilbao',
    'Alicante',
    'Granada',
  ],
  Netherlands: [
    'Amsterdam',
    'Rotterdam',
    'The Hague',
    'Utrecht',
    'Eindhoven',
    'Groningen',
    'Tilburg',
    'Almere',
    'Breda',
    'Nijmegen',
    'Haarlem',
  ],
  Switzerland: [
    'Zurich',
    'Geneva',
    'Basel',
    'Bern',
    'Lausanne',
    'Lucerne',
    'St. Gallen',
    'Lugano',
    'Winterthur',
  ],
  Sweden: [
    'Stockholm',
    'Gothenburg',
    'Malmo',
    'Uppsala',
    'Vasteras',
    'Orebro',
    'Linkoping',
    'Helsingborg',
  ],
  Norway: [
    'Oslo',
    'Bergen',
    'Trondheim',
    'Stavanger',
    'Drammen',
    'Fredrikstad',
    'Kristiansand',
    'Tromso',
  ],
  Denmark: [
    'Copenhagen',
    'Aarhus',
    'Odense',
    'Aalborg',
    'Esbjerg',
    'Randers',
    'Kolding',
  ],
  Ireland: [
    'Dublin',
    'Cork',
    'Galway',
    'Limerick',
    'Waterford',
    'Drogheda',
    'Dundalk',
    'Swords',
  ],
  'New Zealand': [
    'Auckland',
    'Wellington',
    'Christchurch',
    'Hamilton',
    'Tauranga',
    'Dunedin',
    'Palmerston North',
    'Napier-Hastings',
    'Queenstown',
  ],
  'South Africa': [
    'Johannesburg',
    'Cape Town',
    'Durban',
    'Pretoria',
    'Port Elizabeth',
    'Bloemfontein',
    'East London',
    'Pietermaritzburg',
  ],
  Egypt: [
    'Cairo',
    'Alexandria',
    'Giza',
    'Shubra El Kheima',
    'Port Said',
    'Suez',
    'Mansoura',
    'Tanta',
    'Asyut',
    'Ismailia',
    'Aswan',
    'Luxor',
  ],
  Jordan: [
    'Amman',
    'Zarqa',
    'Irbid',
    'Russeifa',
    'Aqaba',
    'Al-Salt',
    'Madaba',
  ],
  Lebanon: [
    'Beirut',
    'Tripoli',
    'Sidon',
    'Tyre',
    'Jounieh',
    'Zahle',
    'Byblos',
  ],
  Morocco: [
    'Casablanca',
    'Rabat',
    'Fes',
    'Marrakech',
    'Tangier',
    'Agadir',
    'Meknes',
    'Oujda',
  ],
  Kenya: [
    'Nairobi',
    'Mombasa',
    'Kisumu',
    'Nakuru',
    'Eldoret',
    'Malindi',
  ],
  Nigeria: [
    'Lagos',
    'Abuja',
    'Kano',
    'Ibadan',
    'Port Harcourt',
    'Benin City',
    'Kaduna',
    'Enugu',
  ],
  Japan: [
    'Tokyo',
    'Osaka',
    'Kyoto',
    'Yokohama',
    'Nagoya',
    'Sapporo',
    'Kobe',
    'Fukuoka',
  ],
  China: [
    'Beijing',
    'Shanghai',
    'Guangzhou',
    'Shenzhen',
    'Chengdu',
    'Hangzhou',
    'Wuhan',
    'Hong Kong',
  ],
  Brazil: [
    'Sao Paulo',
    'Rio de Janeiro',
    'Brasilia',
    'Salvador',
    'Fortaleza',
    'Belo Horizonte',
    'Curitiba',
  ],
  Austria: [
    'Vienna',
    'Graz',
    'Linz',
    'Salzburg',
    'Innsbruck',
    'Klagenfurt',
  ],
  Belgium: [
    'Brussels',
    'Antwerp',
    'Ghent',
    'Charleroi',
    'Liege',
    'Bruges',
  ],
  Greece: [
    'Athens',
    'Thessaloniki',
    'Patras',
    'Heraklion',
    'Larissa',
  ],
  Portugal: [
    'Lisbon',
    'Porto',
    'Vila Nova de Gaia',
    'Amadora',
    'Braga',
    'Funchal',
    'Coimbra',
  ],
  Poland: [
    'Warsaw',
    'Krakow',
    'Lodz',
    'Wroclaw',
    'Poznan',
    'Gdansk',
  ],
  Russia: [
    'Moscow',
    'Saint Petersburg',
    'Novosibirsk',
    'Yekaterinburg',
    'Kazan',
    'Nizhny Novgorod',
  ],
  'South Korea': [
    'Seoul',
    'Busan',
    'Incheon',
    'Daegu',
    'Daejeon',
    'Gwangju',
  ],
  Indonesia: [
    'Jakarta',
    'Surabaya',
    'Bandung',
    'Medan',
    'Bekasi',
    'Semarang',
    'Bali (Denpasar)',
  ],
  Thailand: [
    'Bangkok',
    'Chiang Mai',
    'Phuket',
    'Pattaya',
    'Nonthaburi',
  ],
  'Sri Lanka': [
    'Colombo',
    'Kandy',
    'Galle',
    'Jaffna',
    'Negombo',
    'Batticaloa',
  ],
};

// Full list of world countries (sorted alphabetically with prioritized top diaspora countries first)
export const PRIORITY_COUNTRIES = [
  'Pakistan',
  'United Kingdom',
  'United States',
  'Canada',
  'United Arab Emirates',
  'Saudi Arabia',
  'India',
  'Australia',
  'Germany',
  'Qatar',
  'Kuwait',
  'Oman',
  'Bahrain',
  'Malaysia',
  'Singapore',
  'Bangladesh',
  'Turkey',
  'France',
  'Italy',
  'Spain',
  'Netherlands',
  'Switzerland',
  'Sweden',
  'Norway',
  'Denmark',
  'Ireland',
  'New Zealand',
  'South Africa',
];

export const OTHER_GLOBAL_COUNTRIES = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Argentina',
  'Armenia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Djibouti',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'Gabon',
  'Gambia',
  'Georgia',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'Indonesia',
  'Iran',
  'Iraq',
  'Israel',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kosovo',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Maldives',
  'Mali',
  'Malta',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nepal',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Macedonia',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Romania',
  'Russia',
  'Rwanda',
  'San Marino',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Slovakia',
  'Slovenia',
  'Somalia',
  'South Korea',
  'South Sudan',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Syria',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkmenistan',
  'Uganda',
  'Ukraine',
  'Uruguay',
  'Uzbekistan',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

/**
 * Returns all countries sorted with priority countries first, followed by alphabetical global countries
 */
export function getAllCountries(): string[] {
  const combined = Array.from(new Set([...PRIORITY_COUNTRIES, ...OTHER_GLOBAL_COUNTRIES]));
  return combined;
}

/**
 * Returns sorted list of all countries strictly in alphabetical order
 */
export function getAllCountriesAlphabetical(): string[] {
  return getAllCountries().sort((a, b) => a.localeCompare(b));
}

/**
 * Get cities for a given country name
 */
export function getCitiesForCountry(countryName: string): string[] {
  if (!countryName || countryName === 'ALL') {
    return [];
  }

  // Exact match
  if (COUNTRY_CITIES_MAP[countryName]) {
    return COUNTRY_CITIES_MAP[countryName];
  }

  // Case-insensitive / normalized match
  const foundKey = Object.keys(COUNTRY_CITIES_MAP).find(
    (k) => k.toLowerCase() === countryName.trim().toLowerCase()
  );

  if (foundKey && COUNTRY_CITIES_MAP[foundKey]) {
    return COUNTRY_CITIES_MAP[foundKey];
  }

  // Default fallback cities for generic countries
  return ['Capital City', 'Central District', 'Major Metropolitan Area'];
}
