DROP POLICY IF EXISTS allow_all_users ON public.users;
REVOKE ALL ON TABLE public.users FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_matrimonial_profiles ON public.matrimonial_profiles;
REVOKE ALL ON TABLE public.matrimonial_profiles FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_profile_photos ON public.profile_photos;
REVOKE ALL ON TABLE public.profile_photos FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_education_careers ON public.education_careers;
REVOKE ALL ON TABLE public.education_careers FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_lifestyles ON public.lifestyles;
REVOKE ALL ON TABLE public.lifestyles FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_family_infos ON public.family_infos;
REVOKE ALL ON TABLE public.family_infos FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_partner_preferences ON public.partner_preferences;
REVOKE ALL ON TABLE public.partner_preferences FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_privacy_settings ON public.privacy_settings;
REVOKE ALL ON TABLE public.privacy_settings FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_interest_requests ON public.interest_requests;
REVOKE ALL ON TABLE public.interest_requests FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_favorites ON public.favorites;
REVOKE ALL ON TABLE public.favorites FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_conversations ON public.conversations;
REVOKE ALL ON TABLE public.conversations FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_messages ON public.messages;
REVOKE ALL ON TABLE public.messages FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_notifications ON public.notifications;
REVOKE ALL ON TABLE public.notifications FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_subscription_plans ON public.subscription_plans;
REVOKE ALL ON TABLE public.subscription_plans FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_user_subscriptions ON public.user_subscriptions;
REVOKE ALL ON TABLE public.user_subscriptions FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_invoices ON public.invoices;
REVOKE ALL ON TABLE public.invoices FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_payment_proofs ON public.payment_proofs;
REVOKE ALL ON TABLE public.payment_proofs FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_receiving_accounts ON public.receiving_accounts;
REVOKE ALL ON TABLE public.receiving_accounts FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_verification_requests ON public.verification_requests;
REVOKE ALL ON TABLE public.verification_requests FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_abuse_reports ON public.abuse_reports;
REVOKE ALL ON TABLE public.abuse_reports FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_support_tickets ON public.support_tickets;
REVOKE ALL ON TABLE public.support_tickets FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_ticket_messages ON public.ticket_messages;
REVOKE ALL ON TABLE public.ticket_messages FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_coupons ON public.coupons;
REVOKE ALL ON TABLE public.coupons FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_cms_contents ON public.cms_contents;
REVOKE ALL ON TABLE public.cms_contents FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_admin_audit_logs ON public.admin_audit_logs;
REVOKE ALL ON TABLE public.admin_audit_logs FROM anon, authenticated;
DROP POLICY IF EXISTS allow_all_system_settings ON public.system_settings;
REVOKE ALL ON TABLE public.system_settings FROM anon, authenticated;
