import { createAdminClient } from '@insforge/sdk';
import bcrypt from 'bcryptjs';

const insforgeUrl = process.env.INSFORGE_URL || process.env.NEXT_PUBLIC_INSFORGE_URL || 'https://w5x7768e.us-east.insforge.app';
const insforgeApiKey = process.env.INSFORGE_API_KEY || 'ik_1df0a9cfebae220d87863047d916492b';

const insforgeAdmin = createAdminClient({
  baseUrl: insforgeUrl,
  apiKey: insforgeApiKey,
});

export const ALL_20_PROFILES_DATA = [
  // =========================================================================
  // BOYS (10 Profiles: Hamza Malik #1 + 9 New Boys #2-10)
  // =========================================================================
  {
    num: 1,
    userId: 'user-boy-1',
    profileId: 'profile-boy-1',
    name: 'Dr. Hamza Malik',
    email: 'hamza.malik@gmail.com',
    gender: 'MALE',
    age: 29,
    dob: '1996-04-12',
    city: 'Lahore',
    area: 'Gulberg III',
    caste: 'Malik',
    sect: 'Sunni',
    religion: 'Islam',
    motherTongue: 'Punjabi / Urdu',
    heightCm: 180,
    complexation: 'FAIR',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 300 1122334',
    bioHeadline: 'Cardiologist (FCPS) at Punjab Institute of Cardiology (PIC)',
    aboutMe: 'Practicing Cardiologist at PIC Lahore. Balance religious ethics with professional medical career. Looking for an educated, family-oriented partner with similar values.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'MBBS, FCPS Cardiology',
      highestEducation: 'DOCTORATE',
      institution: 'King Edward Medical University (KEMU)',
      occupation: 'Cardiologist',
      employedIn: 'GOVERNMENT',
      annualIncomePkr: 4200000,
      workLocation: 'Lahore',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'JOINT_FAMILY',
      religiousPractice: 'PRACTICING',
      prayerFrequency: 'ALWAYS_5_TIMES',
      hijabTurban: 'PREFERS_MODEST',
    },
    family: {
      familyType: 'JOINT',
      familyValues: 'MODERATE_RELIGIOUS',
      familyStatus: 'UPPER_MIDDLE',
      fatherOccupation: 'Retired Bureaucrat (Govt of Punjab)',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 2,
      marriedBrothersCount: 1,
      marriedSistersCount: 2,
      nativeCity: 'Lahore',
      familyLocation: 'Gulberg III, Lahore',
    },
    partnerPref: {
      minAge: 23,
      maxAge: 28,
      minHeightCm: 160,
      maxHeightCm: 175,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Sunni',
      caste: 'Malik / Any Respected',
      motherTongue: 'Urdu / Punjabi',
      education: 'Bachelors or Higher (Doctor / Engineer / Professional preferred)',
      occupation: 'Working or Homemaker',
      country: 'Pakistan',
      city: 'Lahore / Islamabad / Rawalpindi',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 2,
    userId: 'user-boy-2',
    profileId: 'profile-boy-2',
    name: 'Engr. Bilal Ahmed',
    email: 'bilal.ahmed@gmail.com',
    gender: 'MALE',
    age: 28,
    dob: '1997-06-15',
    city: 'Islamabad',
    area: 'F-10',
    caste: 'Syed',
    sect: 'Sunni',
    religion: 'Islam',
    motherTongue: 'Urdu',
    heightCm: 182,
    complexation: 'FAIR',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 301 4455667',
    bioHeadline: 'Principal AI/Cloud Architect (NUST) | Tech Consultant',
    aboutMe: 'Lead AI Engineer at a US-based cloud consultancy. NUST graduate with a passion for tech, fitness, and family life. Seeking a compatible, caring life partner.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'MS Computer Science & AI',
      highestEducation: 'MASTERS',
      institution: 'NUST Islamabad',
      occupation: 'Principal AI/Cloud Architect',
      employedIn: 'PRIVATE',
      annualIncomePkr: 5500000,
      workLocation: 'Islamabad',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'NUCLEAR_FAMILY',
      religiousPractice: 'PRACTICING',
      prayerFrequency: 'ALWAYS_5_TIMES',
      hijabTurban: 'MODEST_VALUES',
    },
    family: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE_RELIGIOUS',
      familyStatus: 'UPPER_MIDDLE',
      fatherOccupation: 'Executive Engineer (WAPDA)',
      motherOccupation: 'Associate Professor',
      brothersCount: 1,
      sistersCount: 1,
      marriedBrothersCount: 0,
      marriedSistersCount: 1,
      nativeCity: 'Islamabad',
      familyLocation: 'F-10/2, Islamabad',
    },
    partnerPref: {
      minAge: 22,
      maxAge: 27,
      minHeightCm: 158,
      maxHeightCm: 172,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Sunni',
      caste: 'Syed / Any Educated',
      motherTongue: 'Urdu',
      education: 'Bachelors / Masters',
      occupation: 'Professional / IT / Medical / Any',
      country: 'Pakistan',
      city: 'Islamabad / Rawalpindi / Lahore',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 3,
    userId: 'user-boy-3',
    profileId: 'profile-boy-3',
    name: 'Usman Tariq',
    email: 'usman.tariq@gmail.com',
    gender: 'MALE',
    age: 30,
    dob: '1995-09-22',
    city: 'Karachi',
    area: 'Clifton',
    caste: 'Rajput',
    sect: 'Sunni',
    religion: 'Islam',
    motherTongue: 'Urdu / Punjabi',
    heightCm: 178,
    complexation: 'WHEATISH',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 321 8899001',
    bioHeadline: 'Senior Investment Banker (CFA / IBA Karachi)',
    aboutMe: 'Vice President of M&A and Investment Banking at a leading financial institution in Karachi. IBA alumnus, CFA charterholder. Seeking a graceful, intelligent partner.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'BBA & MBA Finance (IBA), CFA',
      highestEducation: 'MASTERS',
      institution: 'Institute of Business Administration (IBA Karachi)',
      occupation: 'Senior Investment Banker',
      employedIn: 'PRIVATE',
      annualIncomePkr: 6000000,
      workLocation: 'Karachi',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'NUCLEAR_FAMILY',
      religiousPractice: 'MODERATE',
      prayerFrequency: 'REGULAR',
      hijabTurban: 'MODEST_VALUES',
    },
    family: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE_TRADITIONAL',
      familyStatus: 'AFFLUENT',
      fatherOccupation: 'Managing Director (Logistics Co)',
      motherOccupation: 'Homemaker',
      brothersCount: 2,
      sistersCount: 0,
      marriedBrothersCount: 1,
      marriedSistersCount: 0,
      nativeCity: 'Karachi',
      familyLocation: 'Block 4, Clifton, Karachi',
    },
    partnerPref: {
      minAge: 24,
      maxAge: 29,
      minHeightCm: 160,
      maxHeightCm: 175,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Sunni',
      caste: 'Rajput / Any',
      motherTongue: 'Urdu',
      education: 'Graduation / Masters',
      occupation: 'Any',
      country: 'Pakistan',
      city: 'Karachi / Lahore / Islamabad',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 4,
    userId: 'user-boy-4',
    profileId: 'profile-boy-4',
    name: 'Ali Raza Kazmi',
    email: 'ali.raza@gmail.com',
    gender: 'MALE',
    age: 27,
    dob: '1998-03-10',
    city: 'Rawalpindi',
    area: 'Bahria Ph 4',
    caste: 'Syed (Kazmi)',
    sect: 'Shia',
    religion: 'Islam',
    motherTongue: 'Urdu',
    heightCm: 175,
    complexation: 'FAIR',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 333 5566778',
    bioHeadline: 'Chartered Accountant (ACA / LUMS) | Senior Auditor',
    aboutMe: 'Chartered Accountant working with Big 4 Audit Firm. LUMS graduate. High regard for family values, faith, and mutual respect in marriage.',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'BSc Accounting & Finance (LUMS), ACA',
      highestEducation: 'MASTERS',
      institution: 'LUMS & ICAP',
      occupation: 'Chartered Accountant',
      employedIn: 'PRIVATE',
      annualIncomePkr: 3800000,
      workLocation: 'Islamabad / Rawalpindi',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'JOINT_FAMILY',
      religiousPractice: 'PRACTICING',
      prayerFrequency: 'ALWAYS_5_TIMES',
      hijabTurban: 'PREFERS_HIJAB',
    },
    family: {
      familyType: 'JOINT',
      familyValues: 'RELIGIOUS_MODERN',
      familyStatus: 'UPPER_MIDDLE',
      fatherOccupation: 'Civil Judge (Retd)',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 2,
      marriedBrothersCount: 0,
      marriedSistersCount: 2,
      nativeCity: 'Rawalpindi',
      familyLocation: 'Bahria Town Phase 4, Rawalpindi',
    },
    partnerPref: {
      minAge: 21,
      maxAge: 26,
      minHeightCm: 155,
      maxHeightCm: 170,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Shia',
      caste: 'Syed / Kazmi / Any Shia',
      motherTongue: 'Urdu',
      education: 'Bachelors or Masters',
      occupation: 'Working or Homemaker',
      country: 'Pakistan',
      city: 'Rawalpindi / Islamabad / Lahore',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 5,
    userId: 'user-boy-5',
    profileId: 'profile-boy-5',
    name: 'Shahzad Arain',
    email: 'shahzad.arain@gmail.com',
    gender: 'MALE',
    age: 31,
    dob: '1994-11-05',
    city: 'Faisalabad',
    area: 'Civil Lines',
    caste: 'Arain',
    sect: 'Sunni',
    religion: 'Islam',
    motherTongue: 'Punjabi / Urdu',
    heightCm: 183,
    complexation: 'WHEATISH',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 300 7788990',
    bioHeadline: 'Textile Export Director (FAST-NUCES & UK Graduate)',
    aboutMe: 'Director at an established textile export manufacturing firm in Faisalabad. Educated, well-travelled, grounded in family values. Looking for a polite, graceful partner.',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'BS Industrial Engg (FAST), MSc Supply Chain (UK)',
      highestEducation: 'MASTERS',
      institution: 'FAST-NUCES & University of Manchester',
      occupation: 'Textile Export Director',
      employedIn: 'BUSINESS',
      annualIncomePkr: 9500000,
      workLocation: 'Faisalabad',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'JOINT_FAMILY',
      religiousPractice: 'MODERATE',
      prayerFrequency: 'REGULAR',
      hijabTurban: 'MODEST_VALUES',
    },
    family: {
      familyType: 'JOINT',
      familyValues: 'TRADITIONAL_AFFLUENT',
      familyStatus: 'AFFLUENT',
      fatherOccupation: 'Industrialist & Chairman',
      motherOccupation: 'Homemaker',
      brothersCount: 2,
      sistersCount: 1,
      marriedBrothersCount: 1,
      marriedSistersCount: 1,
      nativeCity: 'Faisalabad',
      familyLocation: 'Civil Lines, Faisalabad',
    },
    partnerPref: {
      minAge: 23,
      maxAge: 28,
      minHeightCm: 162,
      maxHeightCm: 175,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Sunni',
      caste: 'Arain / Chaudhry',
      motherTongue: 'Punjabi / Urdu',
      education: 'Bachelors / Masters',
      occupation: 'Any',
      country: 'Pakistan',
      city: 'Faisalabad / Lahore / Islamabad',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 6,
    userId: 'user-boy-6',
    profileId: 'profile-boy-6',
    name: 'Farhan Cheema',
    email: 'farhan.cheema@gmail.com',
    gender: 'MALE',
    age: 28,
    dob: '1997-08-19',
    city: 'Gujranwala',
    area: 'DC Colony',
    caste: 'Jatt (Cheema)',
    sect: 'Sunni',
    religion: 'Islam',
    motherTongue: 'Punjabi / Urdu',
    heightCm: 185,
    complexation: 'FAIR',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 322 3344556',
    bioHeadline: 'Civil Engineer & Construction Contractor (UET Lahore)',
    aboutMe: 'Civil Engineer running family infrastructure construction firm. UET Lahore graduate. Active sportsman, respects family traditions and Islamic values.',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'BSc Civil Engineering (UET Lahore)',
      highestEducation: 'BACHELORS',
      institution: 'UET Lahore',
      occupation: 'Civil Engineer & Contractor',
      employedIn: 'BUSINESS',
      annualIncomePkr: 4800000,
      workLocation: 'Gujranwala / Lahore',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'JOINT_FAMILY',
      religiousPractice: 'PRACTICING',
      prayerFrequency: 'ALWAYS_5_TIMES',
      hijabTurban: 'MODEST_VALUES',
    },
    family: {
      familyType: 'JOINT',
      familyValues: 'MODERATE_RELIGIOUS',
      familyStatus: 'UPPER_MIDDLE',
      fatherOccupation: 'Landowner & Govt Contractor',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 2,
      marriedBrothersCount: 0,
      marriedSistersCount: 2,
      nativeCity: 'Gujranwala',
      familyLocation: 'DC Colony, Gujranwala',
    },
    partnerPref: {
      minAge: 22,
      maxAge: 27,
      minHeightCm: 160,
      maxHeightCm: 175,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Sunni',
      caste: 'Jatt / Cheema / Warraich',
      motherTongue: 'Punjabi / Urdu',
      education: 'Graduate / Medical / Engineering / Teaching',
      occupation: 'Any',
      country: 'Pakistan',
      city: 'Gujranwala / Lahore / Sialkot / Gujrat',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 7,
    userId: 'user-boy-7',
    profileId: 'profile-boy-7',
    name: 'Dr. Hassan Niazi',
    email: 'hassan.niazi@gmail.com',
    gender: 'MALE',
    age: 32,
    dob: '1993-12-14',
    city: 'Peshawar',
    area: 'Hayatabad',
    caste: 'Niazi (Pathan)',
    sect: 'Sunni',
    religion: 'Islam',
    motherTongue: 'Pashto / Urdu',
    heightCm: 181,
    complexation: 'FAIR',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 345 6677889',
    bioHeadline: 'Orthopedic Surgeon (MBBS, MS Ortho) at HMC Peshawar',
    aboutMe: 'Orthopedic Surgeon at Hayatabad Medical Complex. Humble, dedicated, family-centric. Looking for an educated partner from a respected family.',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'MBBS, MS Orthopedic Surgery',
      highestEducation: 'DOCTORATE',
      institution: 'Khyber Medical College (KMC)',
      occupation: 'Orthopedic Surgeon',
      employedIn: 'GOVERNMENT',
      annualIncomePkr: 4500000,
      workLocation: 'Peshawar',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'JOINT_FAMILY',
      religiousPractice: 'PRACTICING',
      prayerFrequency: 'ALWAYS_5_TIMES',
      hijabTurban: 'PREFERS_HIJAB',
    },
    family: {
      familyType: 'JOINT',
      familyValues: 'TRADITIONAL_PASHTUN',
      familyStatus: 'UPPER_MIDDLE',
      fatherOccupation: 'Professor of Surgery (Retd)',
      motherOccupation: 'Homemaker',
      brothersCount: 2,
      sistersCount: 1,
      marriedBrothersCount: 1,
      marriedSistersCount: 1,
      nativeCity: 'Peshawar',
      familyLocation: 'Phase 2, Hayatabad, Peshawar',
    },
    partnerPref: {
      minAge: 23,
      maxAge: 29,
      minHeightCm: 158,
      maxHeightCm: 172,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Sunni',
      caste: 'Niazi / Pathan / Any',
      motherTongue: 'Pashto / Urdu',
      education: 'Doctor (MBBS/BDS) or Master Degree',
      occupation: 'Doctor / Any',
      country: 'Pakistan',
      city: 'Peshawar / Islamabad / Rawalpindi',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 8,
    userId: 'user-boy-8',
    profileId: 'profile-boy-8',
    name: 'Waleed Sheikh',
    email: 'waleed.sheikh@gmail.com',
    gender: 'MALE',
    age: 29,
    dob: '1996-07-28',
    city: 'Sialkot',
    area: 'Model Town',
    caste: 'Sheikh (Siddiqui)',
    sect: 'Sunni',
    religion: 'Islam',
    motherTongue: 'Urdu / Punjabi',
    heightCm: 177,
    complexation: 'FAIR',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 334 9900112',
    bioHeadline: 'Surgical & Sports Goods Exporter (LUMS BSc)',
    aboutMe: 'Managing Partner at ISO-certified surgical instruments export house in Sialkot. LUMS graduate. Modern yet deeply attached to family and ethical values.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'BSc Management Sciences (LUMS)',
      highestEducation: 'BACHELORS',
      institution: 'LUMS Lahore',
      occupation: 'Exporter & Manufacturer',
      employedIn: 'BUSINESS',
      annualIncomePkr: 7200000,
      workLocation: 'Sialkot',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'JOINT_FAMILY',
      religiousPractice: 'MODERATE',
      prayerFrequency: 'REGULAR',
      hijabTurban: 'MODEST_VALUES',
    },
    family: {
      familyType: 'JOINT',
      familyValues: 'MODERATE_RELIGIOUS',
      familyStatus: 'AFFLUENT',
      fatherOccupation: 'Export House Chairman',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 2,
      marriedBrothersCount: 0,
      marriedSistersCount: 2,
      nativeCity: 'Sialkot',
      familyLocation: 'Model Town, Sialkot',
    },
    partnerPref: {
      minAge: 22,
      maxAge: 27,
      minHeightCm: 158,
      maxHeightCm: 172,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Sunni',
      caste: 'Sheikh / Any Educated',
      motherTongue: 'Urdu / Punjabi',
      education: 'Graduation / Masters',
      occupation: 'Any',
      country: 'Pakistan',
      city: 'Sialkot / Lahore / Gujranwala / Islamabad',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 9,
    userId: 'user-boy-9',
    profileId: 'profile-boy-9',
    name: 'Taimoor Abbasi',
    email: 'taimoor.abbasi@gmail.com',
    gender: 'MALE',
    age: 27,
    dob: '1998-10-11',
    city: 'Abbottabad',
    area: 'Cantt',
    caste: 'Abbasi',
    sect: 'Ahle-Hadith',
    religion: 'Islam',
    motherTongue: 'Hindko / Urdu',
    heightCm: 180,
    complexation: 'FAIR',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 312 3322110',
    bioHeadline: 'Assistant Commissioner (PAS / CSS Officer - QAU)',
    aboutMe: 'Civil Servant (Pakistan Administrative Service) allocated through CSS. MPhil from QAU Islamabad. Seeking a righteous, graceful, and educated life companion.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'MPhil Public Policy (QAU), CSS (PAS)',
      highestEducation: 'MASTERS',
      institution: 'Quaid-i-Azam University Islamabad (QAU)',
      occupation: 'Assistant Commissioner / Civil Servant',
      employedIn: 'GOVERNMENT',
      annualIncomePkr: 3200000,
      workLocation: 'KP / Federal',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'NUCLEAR_FAMILY',
      religiousPractice: 'PRACTICING',
      prayerFrequency: 'ALWAYS_5_TIMES',
      hijabTurban: 'PREFERS_HIJAB',
    },
    family: {
      familyType: 'NUCLEAR',
      familyValues: 'RELIGIOUS_EDUCATED',
      familyStatus: 'UPPER_MIDDLE',
      fatherOccupation: 'Brigadier (Retd), Pak Army',
      motherOccupation: 'Senior Educationist',
      brothersCount: 1,
      sistersCount: 1,
      marriedBrothersCount: 0,
      marriedSistersCount: 1,
      nativeCity: 'Abbottabad',
      familyLocation: 'Cantt, Abbottabad',
    },
    partnerPref: {
      minAge: 21,
      maxAge: 26,
      minHeightCm: 156,
      maxHeightCm: 172,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Ahle-Hadith / Sunni',
      caste: 'Abbasi / Any Respectable',
      motherTongue: 'Urdu / Hindko',
      education: 'Masters / Graduation',
      occupation: 'Civil Service / Medical / Teaching / Homemaker',
      country: 'Pakistan',
      city: 'Islamabad / Rawalpindi / Abbottabad / Peshawar',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 10,
    userId: 'user-boy-10',
    profileId: 'profile-boy-10',
    name: 'Danyal Memon',
    email: 'danyal.memon@gmail.com',
    gender: 'MALE',
    age: 28,
    dob: '1997-04-03',
    city: 'Karachi',
    area: 'PECHS',
    caste: 'Memon',
    sect: 'Sunni',
    religion: 'Islam',
    motherTongue: 'Sindhi / Memoni / Urdu',
    heightCm: 176,
    complexation: 'WHEATISH',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 300 4433221',
    bioHeadline: 'Fintech Product Lead (GIKI Alum) | Tech Entrepreneur',
    aboutMe: 'Product Lead at a leading digital bank in Karachi. GIKI engineering graduate. Modern mindset with strong respect for Memon traditions and cultural harmony.',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'BS Computer Systems Engg (GIKI)',
      highestEducation: 'BACHELORS',
      institution: 'GIK Institute of Engineering Sciences and Technology',
      occupation: 'Fintech Product Lead',
      employedIn: 'PRIVATE',
      annualIncomePkr: 4500000,
      workLocation: 'Karachi',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'JOINT_FAMILY',
      religiousPractice: 'MODERATE',
      prayerFrequency: 'REGULAR',
      hijabTurban: 'MODEST_VALUES',
    },
    family: {
      familyType: 'JOINT',
      familyValues: 'MODERATE_TRADITIONAL',
      familyStatus: 'UPPER_MIDDLE',
      fatherOccupation: 'Wholesale Commodity Merchant',
      motherOccupation: 'Homemaker',
      brothersCount: 2,
      sistersCount: 1,
      marriedBrothersCount: 1,
      marriedSistersCount: 1,
      nativeCity: 'Karachi',
      familyLocation: 'Block 2, PECHS, Karachi',
    },
    partnerPref: {
      minAge: 22,
      maxAge: 27,
      minHeightCm: 155,
      maxHeightCm: 170,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Sunni',
      caste: 'Memon / Any',
      motherTongue: 'Urdu / Memoni / Sindhi',
      education: 'Graduation / Masters',
      occupation: 'Any',
      country: 'Pakistan',
      city: 'Karachi / Hyderabad / Islamabad',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },

  // =========================================================================
  // GIRLS (10 Profiles: Amna Khan #1 + 9 New Girls #2-10)
  // =========================================================================
  {
    num: 1,
    userId: 'user-amna',
    profileId: 'profile-amna',
    name: 'Amna Khan',
    email: 'amna.khan@gmail.com',
    gender: 'FEMALE',
    age: 25,
    dob: '2000-05-18',
    city: 'Lahore',
    area: 'DHA Phase 5',
    caste: 'Khan (Yousafzai)',
    sect: 'Sunni',
    religion: 'Islam',
    motherTongue: 'Urdu',
    heightCm: 165,
    complexation: 'VERY_FAIR',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 300 1234567',
    bioHeadline: 'Senior Clinical Psychologist (MSc King Edward Medical University)',
    aboutMe: 'Clinical Psychologist practicing in DHA Lahore. Compassionate, grounded in religious principles, family-oriented. Enjoys reading, creative interior arts, and community service.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'MSc Clinical Psychology, MS Child Psychology',
      highestEducation: 'MASTERS',
      institution: 'King Edward Medical University (KEMU)',
      occupation: 'Clinical Psychologist',
      employedIn: 'PRIVATE',
      annualIncomePkr: 2800000,
      workLocation: 'Lahore',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'FLEXIBLE',
      religiousPractice: 'PRACTICING',
      prayerFrequency: 'ALWAYS_5_TIMES',
      hijabTurban: 'PREFERS_HIJAB',
    },
    family: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE_RELIGIOUS',
      familyStatus: 'UPPER_MIDDLE',
      fatherOccupation: 'Executive Vice President (Habib Bank Ltd)',
      motherOccupation: 'Senior School Principal (Beaconhouse)',
      brothersCount: 1,
      sistersCount: 1,
      marriedBrothersCount: 0,
      marriedSistersCount: 0,
      nativeCity: 'Lahore',
      familyLocation: 'Sector C, DHA Phase 5, Lahore',
    },
    partnerPref: {
      minAge: 27,
      maxAge: 32,
      minHeightCm: 175,
      maxHeightCm: 188,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Sunni',
      caste: 'Pathan / Any Respectable Muslim Caste',
      motherTongue: 'Urdu / Punjabi / Pashto',
      education: 'Masters or Higher (Doctor / Engineer / CSP / Business Owner)',
      occupation: 'Doctor / Engineer / Executive / Civil Service',
      country: 'Pakistan',
      city: 'Lahore / Islamabad / Rawalpindi',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 2,
    userId: 'user-girl-2',
    profileId: 'profile-girl-2',
    name: 'Dr. Zainab Qureshi',
    email: 'zainab.qureshi@gmail.com',
    gender: 'FEMALE',
    age: 26,
    dob: '1999-08-24',
    city: 'Islamabad',
    area: 'G-11',
    caste: 'Qureshi / Syed',
    sect: 'Sunni',
    religion: 'Islam',
    motherTongue: 'Urdu',
    heightCm: 168,
    complexation: 'VERY_FAIR',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 333 1122445',
    bioHeadline: 'Resident Medical Officer (MBBS Shifa International Hospital)',
    aboutMe: 'MBBS Doctor at Shifa International Hospital Islamabad. Preparing for FCPS Part 2. Soft-spoken, religious, family-oriented. Looking for a doctor, civil servant, or corporate professional.',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'MBBS (Shifa College of Medicine)',
      highestEducation: 'DOCTORATE',
      institution: 'Shifa Tameer-e-Millat University',
      occupation: 'Resident Medical Officer',
      employedIn: 'PRIVATE',
      annualIncomePkr: 2400000,
      workLocation: 'Islamabad',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'FLEXIBLE',
      religiousPractice: 'PRACTICING',
      prayerFrequency: 'ALWAYS_5_TIMES',
      hijabTurban: 'PREFERS_HIJAB',
    },
    family: {
      familyType: 'NUCLEAR',
      familyValues: 'RELIGIOUS_EDUCATED',
      familyStatus: 'UPPER_MIDDLE',
      fatherOccupation: 'Federal Secretary (Retd)',
      motherOccupation: 'Associate Professor of Botany',
      brothersCount: 1,
      sistersCount: 1,
      marriedBrothersCount: 0,
      marriedSistersCount: 1,
      nativeCity: 'Islamabad',
      familyLocation: 'G-11/3, Islamabad',
    },
    partnerPref: {
      minAge: 27,
      maxAge: 32,
      minHeightCm: 175,
      maxHeightCm: 188,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Sunni',
      caste: 'Qureshi / Syed / Any Educated',
      motherTongue: 'Urdu',
      education: 'MBBS / FCPS / Engg / CSP / Masters',
      occupation: 'Doctor / Civil Servant / Engineer / Executive',
      country: 'Pakistan',
      city: 'Islamabad / Rawalpindi / Lahore',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 3,
    userId: 'user-girl-3',
    profileId: 'profile-girl-3',
    name: 'Fatima Zahra Kazmi',
    email: 'fatima.zahra@gmail.com',
    gender: 'FEMALE',
    age: 24,
    dob: '2001-02-14',
    city: 'Lahore',
    area: 'Model Town',
    caste: 'Syed (Kazmi)',
    sect: 'Shia',
    religion: 'Islam',
    motherTongue: 'Urdu',
    heightCm: 163,
    complexation: 'FAIR',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 321 9988776',
    bioHeadline: 'Software Engineer & UI Lead (LUMS CS Alum)',
    aboutMe: 'LUMS Computer Science graduate working as Senior UI/UX Engineer at a Silicon Valley startup remote office. Practicing Shia Syed family with high academic values.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'BSc Computer Science (LUMS)',
      highestEducation: 'BACHELORS',
      institution: 'LUMS Lahore',
      occupation: 'Software Engineer & UI Lead',
      employedIn: 'PRIVATE',
      annualIncomePkr: 3600000,
      workLocation: 'Lahore (Remote)',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'FLEXIBLE',
      religiousPractice: 'PRACTICING',
      prayerFrequency: 'ALWAYS_5_TIMES',
      hijabTurban: 'PREFERS_HIJAB',
    },
    family: {
      familyType: 'NUCLEAR',
      familyValues: 'RELIGIOUS_MODERN',
      familyStatus: 'UPPER_MIDDLE',
      fatherOccupation: 'Senior Advocate Supreme Court',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      marriedBrothersCount: 0,
      marriedSistersCount: 0,
      nativeCity: 'Lahore',
      familyLocation: 'Block C, Model Town, Lahore',
    },
    partnerPref: {
      minAge: 26,
      maxAge: 31,
      minHeightCm: 172,
      maxHeightCm: 185,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Shia',
      caste: 'Syed (Kazmi/Rizvi/Zaidi)',
      motherTongue: 'Urdu',
      education: 'Graduation / Masters (IT / Finance / Engineering / Medical)',
      occupation: 'Software Engineer / Doctor / CA / Business',
      country: 'Pakistan',
      city: 'Lahore / Islamabad / Karachi',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 4,
    userId: 'user-girl-4',
    profileId: 'profile-girl-4',
    name: 'Areeba Rajput',
    email: 'areeba.rajput@gmail.com',
    gender: 'FEMALE',
    age: 26,
    dob: '1999-11-09',
    city: 'Rawalpindi',
    area: 'Chaklala',
    caste: 'Rajput',
    sect: 'Sunni',
    religion: 'Islam',
    motherTongue: 'Urdu / Punjabi',
    heightCm: 167,
    complexation: 'FAIR',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 301 7766554',
    bioHeadline: 'Senior Corporate Lawyer (LLM Queen Mary University of London)',
    aboutMe: 'Corporate & Commercial Associate at a top tier Islamabad law firm. LLM from London. Passionate about law, balanced lifestyle, and cultural harmony.',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'LLB (Hons), LLM Commercial Law (London)',
      highestEducation: 'MASTERS',
      institution: 'Queen Mary University of London',
      occupation: 'Senior Corporate Lawyer',
      employedIn: 'PRIVATE',
      annualIncomePkr: 3200000,
      workLocation: 'Islamabad / Rawalpindi',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'NUCLEAR_FAMILY',
      religiousPractice: 'MODERATE',
      prayerFrequency: 'REGULAR',
      hijabTurban: 'MODEST_VALUES',
    },
    family: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE_EDUCATED',
      familyStatus: 'UPPER_MIDDLE',
      fatherOccupation: 'Major General (Retd), Pak Army',
      motherOccupation: 'Homemaker',
      brothersCount: 2,
      sistersCount: 0,
      marriedBrothersCount: 1,
      marriedSistersCount: 0,
      nativeCity: 'Rawalpindi',
      familyLocation: 'Chaklala Scheme 3, Rawalpindi',
    },
    partnerPref: {
      minAge: 27,
      maxAge: 32,
      minHeightCm: 175,
      maxHeightCm: 188,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Sunni',
      caste: 'Rajput / Any Educated Army/Civilian Family',
      motherTongue: 'Urdu / Punjabi',
      education: 'Masters / Professional (Army Officer / CSS / Lawyer / Engineer)',
      occupation: 'Army Officer / CSP / Corporate / Business',
      country: 'Pakistan',
      city: 'Rawalpindi / Islamabad / Lahore',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 5,
    userId: 'user-girl-5',
    profileId: 'profile-girl-5',
    name: 'Mariam Arain',
    email: 'mariam.arain@gmail.com',
    gender: 'FEMALE',
    age: 25,
    dob: '2000-09-12',
    city: 'Faisalabad',
    area: 'Peoples Col',
    caste: 'Arain',
    sect: 'Sunni',
    religion: 'Islam',
    motherTongue: 'Punjabi / Urdu',
    heightCm: 162,
    complexation: 'FAIR',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 300 8877665',
    bioHeadline: 'Lecturer of English Literature (MPhil GCUF)',
    aboutMe: 'Lecturer at Govt College for Women Faisalabad. MPhil English Literature with distinction. Elegant, gentle, respectful of elders and traditional family values.',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'BS & MPhil English Literature (Gold Medalist)',
      highestEducation: 'MASTERS',
      institution: 'GC University Faisalabad',
      occupation: 'Lecturer in English',
      employedIn: 'GOVERNMENT',
      annualIncomePkr: 1800000,
      workLocation: 'Faisalabad',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'JOINT_FAMILY',
      religiousPractice: 'PRACTICING',
      prayerFrequency: 'ALWAYS_5_TIMES',
      hijabTurban: 'PREFERS_HIJAB',
    },
    family: {
      familyType: 'JOINT',
      familyValues: 'MODERATE_RELIGIOUS',
      familyStatus: 'UPPER_MIDDLE',
      fatherOccupation: 'Landowner & Agriculturalist',
      motherOccupation: 'Homemaker',
      brothersCount: 2,
      sistersCount: 1,
      marriedBrothersCount: 1,
      marriedSistersCount: 0,
      nativeCity: 'Faisalabad',
      familyLocation: 'Peoples Colony No. 1, Faisalabad',
    },
    partnerPref: {
      minAge: 27,
      maxAge: 31,
      minHeightCm: 172,
      maxHeightCm: 185,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Sunni',
      caste: 'Arain / Chaudhry',
      motherTongue: 'Punjabi / Urdu',
      education: 'Bachelors / Masters / Civil Service / Business',
      occupation: 'Industrialist / Govt Officer / Engineer / Doctor',
      country: 'Pakistan',
      city: 'Faisalabad / Lahore / Islamabad',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 6,
    userId: 'user-girl-6',
    profileId: 'profile-girl-6',
    name: 'Hira Siddiqui',
    email: 'hira.siddiqui@gmail.com',
    gender: 'FEMALE',
    age: 27,
    dob: '1998-05-30',
    city: 'Karachi',
    area: 'Gulshan-e-Iqbal',
    caste: 'Sheikh (Siddiqui)',
    sect: 'Sunni',
    religion: 'Islam',
    motherTongue: 'Urdu',
    heightCm: 164,
    complexation: 'FAIR',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 334 2233445',
    bioHeadline: 'Audit Manager & ACCA Member (Big 4 Pakistan)',
    aboutMe: 'Audit Manager at leading international accounting firm in Karachi. Member of ACCA UK. Well-mannered, family-oriented, balancing career and home values.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'ACCA Member, BSc Applied Accounting (Oxford Brookes)',
      highestEducation: 'MASTERS',
      institution: 'ACCA UK & Oxford Brookes University',
      occupation: 'Audit Manager (Chartered Certified Accountant)',
      employedIn: 'PRIVATE',
      annualIncomePkr: 3000000,
      workLocation: 'Karachi',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'NUCLEAR_FAMILY',
      religiousPractice: 'MODERATE',
      prayerFrequency: 'REGULAR',
      hijabTurban: 'MODEST_VALUES',
    },
    family: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE_EDUCATED',
      familyStatus: 'UPPER_MIDDLE',
      fatherOccupation: 'Chartered Accountant (Partner Retd)',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 2,
      marriedBrothersCount: 0,
      marriedSistersCount: 2,
      nativeCity: 'Karachi',
      familyLocation: 'Block 6, Gulshan-e-Iqbal, Karachi',
    },
    partnerPref: {
      minAge: 28,
      maxAge: 33,
      minHeightCm: 172,
      maxHeightCm: 185,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Sunni',
      caste: 'Sheikh / Siddiqui / Ansari / Any Urdu Speaking',
      motherTongue: 'Urdu',
      education: 'Chartered Accountant / MBA / Engineering / Medical',
      occupation: 'CA / Banker / Software Engg / Business',
      country: 'Pakistan',
      city: 'Karachi / Islamabad / Lahore',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 7,
    userId: 'user-girl-7',
    profileId: 'profile-girl-7',
    name: 'Noor-ul-Ain Malik',
    email: 'noor.malik@gmail.com',
    gender: 'FEMALE',
    age: 24,
    dob: '2001-08-05',
    city: 'Multan',
    area: 'Cantt',
    caste: 'Malik (Awan)',
    sect: 'Sunni',
    religion: 'Islam',
    motherTongue: 'Saraiki / Urdu',
    heightCm: 166,
    complexation: 'VERY_FAIR',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 308 1122339',
    bioHeadline: 'CSS Aspirant & Gold Medalist in Political Science (BZU)',
    aboutMe: 'Graduated top of class from BZU Multan. Currently preparing for Civil Services Examinations (CSS). Calm, pious, deeply rooted in family and moral values.',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'BS Political Science & International Relations (Gold Medalist)',
      highestEducation: 'BACHELORS',
      institution: 'Bahauddin Zakariya University Multan',
      occupation: 'CSS Aspirant & Academic Researcher',
      employedIn: 'GOVERNMENT',
      annualIncomePkr: 1500000,
      workLocation: 'Multan / Islamabad',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'JOINT_FAMILY',
      religiousPractice: 'PRACTICING',
      prayerFrequency: 'ALWAYS_5_TIMES',
      hijabTurban: 'PREFERS_HIJAB',
    },
    family: {
      familyType: 'JOINT',
      familyValues: 'MODERATE_RELIGIOUS',
      familyStatus: 'UPPER_MIDDLE',
      fatherOccupation: 'Executive Engineer (Irrigation Dept)',
      motherOccupation: 'Homemaker',
      brothersCount: 2,
      sistersCount: 0,
      marriedBrothersCount: 1,
      marriedSistersCount: 0,
      nativeCity: 'Multan',
      familyLocation: 'Officers Colony, Cantt, Multan',
    },
    partnerPref: {
      minAge: 26,
      maxAge: 31,
      minHeightCm: 175,
      maxHeightCm: 188,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Sunni',
      caste: 'Malik / Awan / Any Respected',
      motherTongue: 'Saraiki / Urdu / Punjabi',
      education: 'CSP / Civil Service / Doctor / Engineer / Masters',
      occupation: 'Civil Servant / Doctor / Engineer / Army Officer',
      country: 'Pakistan',
      city: 'Multan / Lahore / Islamabad',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 8,
    userId: 'user-girl-8',
    profileId: 'profile-girl-8',
    name: 'Ayesha Butt',
    email: 'ayesha.butt@gmail.com',
    gender: 'FEMALE',
    age: 26,
    dob: '1999-04-16',
    city: 'Lahore',
    area: 'Johar Town',
    caste: 'Butt (Kashmiri)',
    sect: 'Sunni',
    religion: 'Islam',
    motherTongue: 'Urdu / Punjabi',
    heightCm: 165,
    complexation: 'VERY_FAIR',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 323 4455667',
    bioHeadline: 'Senior Clinical Nutritionist & Dietitian (MPhil UVAS)',
    aboutMe: 'Clinical Nutritionist at a premier private hospital in Lahore. MPhil from UVAS. Caring, enthusiastic, culinary hobbyist with strong family ethics.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'MPhil Food and Clinical Nutrition',
      highestEducation: 'MASTERS',
      institution: 'University of Veterinary and Animal Sciences (UVAS Lahore)',
      occupation: 'Clinical Nutritionist',
      employedIn: 'PRIVATE',
      annualIncomePkr: 2200000,
      workLocation: 'Lahore',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'FLEXIBLE',
      religiousPractice: 'MODERATE',
      prayerFrequency: 'ALWAYS_5_TIMES',
      hijabTurban: 'MODEST_VALUES',
    },
    family: {
      familyType: 'NUCLEAR',
      familyValues: 'MODERATE_RELIGIOUS',
      familyStatus: 'UPPER_MIDDLE',
      fatherOccupation: 'Wholesale Electronics Distributor',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 2,
      marriedBrothersCount: 0,
      marriedSistersCount: 1,
      nativeCity: 'Lahore',
      familyLocation: 'Block F, Johar Town, Lahore',
    },
    partnerPref: {
      minAge: 27,
      maxAge: 32,
      minHeightCm: 175,
      maxHeightCm: 188,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Sunni',
      caste: 'Kashmiri Butt / Dar / Lone / Any',
      motherTongue: 'Urdu / Punjabi',
      education: 'Bachelors / Masters / Business',
      occupation: 'Business Owner / Engineer / Doctor / IT Professional',
      country: 'Pakistan',
      city: 'Lahore / Islamabad / Rawalpindi',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 9,
    userId: 'user-girl-9',
    profileId: 'profile-girl-9',
    name: 'Dr. Mahnoor Gujjar',
    email: 'mahnoor.gujjar@gmail.com',
    gender: 'FEMALE',
    age: 27,
    dob: '1998-12-01',
    city: 'Gujrat',
    area: 'Court Road',
    caste: 'Gujjar (Chaudhry)',
    sect: 'Sunni',
    religion: 'Islam',
    motherTongue: 'Punjabi / Urdu',
    heightCm: 166,
    complexation: 'FAIR',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 300 9988112',
    bioHeadline: 'Dental Surgeon (BDS, RDS de\'Montmorency College of Dentistry)',
    aboutMe: 'Dental Surgeon at DHQ Teaching Hospital Gujrat. Graduate of de\'Montmorency Lahore. Dignified, polite, and devoted to family and clinical excellence.',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'BDS (Dental Surgery), RDS PMDC Verified',
      highestEducation: 'DOCTORATE',
      institution: 'de\'Montmorency College of Dentistry Lahore',
      occupation: 'Dental Surgeon',
      employedIn: 'GOVERNMENT',
      annualIncomePkr: 2600000,
      workLocation: 'Gujrat',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'JOINT_FAMILY',
      religiousPractice: 'PRACTICING',
      prayerFrequency: 'ALWAYS_5_TIMES',
      hijabTurban: 'PREFERS_HIJAB',
    },
    family: {
      familyType: 'JOINT',
      familyValues: 'MODERATE_RELIGIOUS',
      familyStatus: 'UPPER_MIDDLE',
      fatherOccupation: 'Senior Civil Judge (Retd)',
      motherOccupation: 'Homemaker',
      brothersCount: 2,
      sistersCount: 1,
      marriedBrothersCount: 1,
      marriedSistersCount: 0,
      nativeCity: 'Gujrat',
      familyLocation: 'Court Road, Gujrat',
    },
    partnerPref: {
      minAge: 28,
      maxAge: 33,
      minHeightCm: 175,
      maxHeightCm: 188,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Sunni',
      caste: 'Gujjar / Chaudhry / Jatt',
      motherTongue: 'Punjabi / Urdu',
      education: 'Doctor (MBBS/FCPS) / Civil Servant / Engineer',
      occupation: 'Doctor / CSP / Engineer / Landowner',
      country: 'Pakistan',
      city: 'Gujrat / Lahore / Islamabad / Sialkot',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
  {
    num: 10,
    userId: 'user-girl-10',
    profileId: 'profile-girl-10',
    name: 'Sara Abbasi',
    email: 'sara.abbasi@gmail.com',
    gender: 'FEMALE',
    age: 25,
    dob: '2000-06-20',
    city: 'Islamabad',
    area: 'I-8',
    caste: 'Abbasi',
    sect: 'Ahle-Hadith',
    religion: 'Islam',
    motherTongue: 'Urdu / Hindko',
    heightCm: 164,
    complexation: 'VERY_FAIR',
    maritalStatus: 'NEVER_MARRIED',
    physicalStatus: 'NORMAL',
    citizenship: 'Pakistani',
    phone: '+92 313 7788990',
    bioHeadline: 'Interior Architect & 3D Visualizer (NCA Lahore Alum)',
    aboutMe: 'B.Arch from National College of Arts (NCA). Senior Architect at a leading design firm in Islamabad. Respects religious principles, artistic lifestyle, and strong home culture.',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    education: {
      degree: 'Bachelor of Architecture (B.Arch NCA)',
      highestEducation: 'BACHELORS',
      institution: 'National College of Arts (NCA Lahore)',
      occupation: 'Interior Architect & 3D Visualizer',
      employedIn: 'PRIVATE',
      annualIncomePkr: 2500000,
      workLocation: 'Islamabad',
    },
    lifestyle: {
      diet: 'HALAL_STRICT',
      smoking: 'NON_SMOKER',
      drinking: 'NEVER',
      livingArrangement: 'NUCLEAR_FAMILY',
      religiousPractice: 'PRACTICING',
      prayerFrequency: 'ALWAYS_5_TIMES',
      hijabTurban: 'PREFERS_HIJAB',
    },
    family: {
      familyType: 'NUCLEAR',
      familyValues: 'RELIGIOUS_EDUCATED',
      familyStatus: 'UPPER_MIDDLE',
      fatherOccupation: 'Director General (Retd), CDA',
      motherOccupation: 'Homemaker',
      brothersCount: 1,
      sistersCount: 1,
      marriedBrothersCount: 0,
      marriedSistersCount: 1,
      nativeCity: 'Islamabad',
      familyLocation: 'Sector I-8/2, Islamabad',
    },
    partnerPref: {
      minAge: 27,
      maxAge: 32,
      minHeightCm: 175,
      maxHeightCm: 188,
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Islam',
      sect: 'Ahle-Hadith / Sunni',
      caste: 'Abbasi / Any Respected',
      motherTongue: 'Urdu',
      education: 'Masters / Graduation (Engineer / Architect / IT / Civil Servant)',
      occupation: 'Architect / Software Engineer / Civil Servant / Corporate Executive',
      country: 'Pakistan',
      city: 'Islamabad / Rawalpindi / Lahore',
      smokingAcceptable: 'NO',
      drinkingAcceptable: 'NO',
    },
  },
];

async function withRetry<T>(fn: () => Promise<T>, retries = 3, delayMs = 1000): Promise<T> {
  try {
    return await fn();
  } catch (err) {
    if (retries <= 1) throw err;
    await new Promise((r) => setTimeout(r, delayMs));
    return withRetry(fn, retries - 1, delayMs * 1.5);
  }
}

async function seedProfiles() {
  console.log('🌱 Starting Seeding of 10 Pakistani Boys & 10 Pakistani Girls Profiles in InsForge DB...\n');

  const commonPasswordHash = await bcrypt.hash('password123', 10);
  const ladiPasswordHash = await bcrypt.hash('ladi02893', 10);

  // 1. First ensure Super Admin user exists
  const superAdminUser = {
    id: 'user-ladi',
    email: 'ladi02893@gmail.com',
    password_hash: ladiPasswordHash,
    name: 'Ladi (Super Admin)',
    role: 'SUPER_ADMIN',
    subscription_tier: 'PREMIUM_PLUS',
    is_verified: true,
    account_status: 'ACTIVE',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
  };

  await withRetry(async () => {
    const { error } = await insforgeAdmin.database.from('users').upsert([superAdminUser]);
    if (error) throw new Error(error.message);
  });
  console.log('✓ Super Admin verified in InsForge DB.');

  // 2. Iterate through all 20 Profiles
  for (const item of ALL_20_PROFILES_DATA) {
    const isAmna = item.userId === 'user-amna';
    // User Record
    const userPayload = {
      id: item.userId,
      email: item.email,
      password_hash: commonPasswordHash,
      name: item.name,
      role: 'USER',
      subscription_tier: isAmna ? 'PREMIUM_PLUS' : 'FREE',
      is_verified: true,
      account_status: 'ACTIVE',
      avatar_url: item.avatarUrl,
    };

    await withRetry(async () => {
      const { error } = await insforgeAdmin.database.from('users').upsert([userPayload]);
      if (error) throw new Error(error.message);
    });

    // Profile Record
    const profilePayload = {
      id: item.profileId,
      user_id: item.userId,
      profile_created_for: 'SELF',
      full_name: item.name,
      display_name: item.name.split(' ')[0],
      gender: item.gender,
      date_of_birth: new Date(item.dob).toISOString(),
      marital_status: item.maritalStatus,
      religion: 'ISLAM',
      sect_or_community: item.sect,
      caste_or_sub_clan: item.caste,
      mother_tongue: item.motherTongue,
      country: 'Pakistan',
      state_province: 'Punjab',
      city: item.city,
      bio_headline: item.bioHeadline,
      about_me: item.aboutMe,
      completion_percentage: 95,
      view_count: 10 + Math.floor(Math.random() * 40),
      like_count: 3 + Math.floor(Math.random() * 15),
    };

    await withRetry(async () => {
      const { error } = await insforgeAdmin.database.from('matrimonial_profiles').upsert([profilePayload]);
      if (error) throw new Error(error.message);
    });

    // Child records: EducationCareer, Lifestyle, FamilyInfo, PartnerPreferences, PrivacySettings
    await withRetry(async () => {
      await insforgeAdmin.database.from('education_careers').delete().eq('profile_id', item.profileId);
      await insforgeAdmin.database.from('lifestyles').delete().eq('profile_id', item.profileId);
      await insforgeAdmin.database.from('family_infos').delete().eq('profile_id', item.profileId);
      await insforgeAdmin.database.from('partner_preferences').delete().eq('profile_id', item.profileId);
      await insforgeAdmin.database.from('privacy_settings').delete().eq('profile_id', item.profileId);
      await insforgeAdmin.database.from('profile_photos').delete().eq('profile_id', item.profileId);

      await insforgeAdmin.database.from('education_careers').insert([{
        profile_id: item.profileId,
        highest_degree: item.education.degree,
        institution: item.education.institution,
        profession: item.education.occupation,
        annual_income: `PKR ${(item.education.annualIncomePkr / 1000000).toFixed(1)} Million`,
        currency: 'PKR',
      }]);

      await insforgeAdmin.database.from('lifestyles').insert([{
        profile_id: item.profileId,
        height: `${Math.floor(item.heightCm / 30.48)}' ${Math.round((item.heightCm % 30.48) / 2.54)}"`,
        weight: '68 kg',
        diet: 'HALAL_ONLY',
        smoking: 'NO',
        drinking: 'NO',
        mother_tongue: item.motherTongue,
        languages_spoken: ['English', 'Urdu'],
      }]);

      await insforgeAdmin.database.from('family_infos').insert([{
        profile_id: item.profileId,
        family_type: item.family.familyType,
        family_values: item.family.familyValues,
        father_occupation: item.family.fatherOccupation,
        mother_occupation: item.family.motherOccupation,
        brothers_count: item.family.brothersCount,
        sisters_count: item.family.sistersCount,
        family_location: item.family.familyLocation,
        about_family: `${item.caste} family with high academic and moral values residing in ${item.city}.`,
      }]);

      await insforgeAdmin.database.from('partner_preferences').insert([{
        profile_id: item.profileId,
        min_age: item.partnerPref.minAge,
        max_age: item.partnerPref.maxAge,
        marital_statuses: ['NEVER_MARRIED'],
        religions: ['ISLAM'],
        expectations_notes: `Seeking an educated, sincere partner from a respectable family. ${item.partnerPref.education}`,
      }]);

      await insforgeAdmin.database.from('privacy_settings').insert([{
        profile_id: item.profileId,
        photo_visibility: 'ALL',
        contact_visibility: 'ONLY_ACCEPTED_INTERESTS',
        show_age: true,
        show_income: true,
      }]);

      await insforgeAdmin.database.from('profile_photos').insert([{
        profile_id: item.profileId,
        url: item.avatarUrl,
        is_primary: true,
        is_approved: true,
        order_num: 1,
      }]);
    });

    console.log(`  ✓ Seeded [${item.gender} #${item.num}]: ${item.name} (${item.email}) - ${item.city} | ${item.caste} | ${item.education.degree}`);
    // Short 200ms delay between profiles to avoid rate limits
    await new Promise((r) => setTimeout(r, 200));
  }

  console.log('\n🎉 ALL 20 PAKISTANI PROFILES & USERS SUCCESSFULLY INSERTED INTO INSFORGE POSTGRESQL DATABASE!');
}

seedProfiles().catch(console.error);
